### ISSUE TITLE
Wells: What kind of content should go in wells? Content enhancement / info incorrect

### ISSUE THREAD

**Issue by sonnakim** [cfpb/design-system#1007]
**Which page is this about?** 
https://cfpb.github.io/design-system/patterns/wells#guidelines

**What kind of issue is this?**
- [x] Info incorrect 
- [x] Content enhancement (e.g. confusing or redundant content, small content items need to be added, etc.) 

**Describe your issue** 
Under https://cfpb.github.io/design-system/patterns/wells#guidelines, it says we can add images and video to wells. Is that true? Should we show an example here, if so?
 
**Size this request (1=tiny, 5=enormous)**
1?

**Comment by sonnakim** [comment]
After discussing this with @huetingj , we've decided to remove this guidance from the design system, because there are much more preferable ways of adding images and videos, such as the featured content module.

**Comment by sonnakim** [comment]
Hokay. I changed the copy from 
 
> Text, images, and embedded media (like video) may be placed within wells, however, if content includes imagery, also consider the featured content module. Examples of types of content to include:

to

> Wells should generally be text-based. If content must include imagery or videos, use the featured content module instead. Examples of types of content to include:

I could have used stronger language ("Wells should always be text-based"), but softened with the word "generally"  because I know of at least one (weird) exception to this rule about wells, on the complaint page. So, in general, we should not be putting anything other than text into wells, but there may have to be occasional exceptions. 

I'm happy to make this language stricter, though. Or conversely, if anyone knows of additional, legitimate examples/use cases of wells with imagery or video, please chime in.

**Comment by stephanieosan** [comment]
@sonnakim Is this done?

**Comment by sonnakim** [comment]
I think so!
