### ISSUE TITLE
Email sign up forms: Inset email module needs code snippet

### ISSUE THREAD

**Issue by sonnakim** [cfpb/design-system#1010]
**Which page is this about?** 
https://cfpb.github.io/design-system/patterns/e-mail-signup-forms#types-1

**What kind of issue is this?**
Add one or more of the issue labels below to the right-hand sidebar AND issue title. 
(We strongly encourage you to make content changes yourself where possible!)
-  Needs code snippet
 

**Describe your issue** 
Add code snippets for both sidebar and inset email examples in [the types section](https://cfpb.github.io/design-system/patterns/e-mail-signup-forms#types-1)
 
**Size this request (1=tiny, 5=enormous)**
3 

**Add any additional background info as needed** 
Make sure NOT to include internal links.

***Thanks. Don't forget to add labels indicating issue type and size before submitting!***
***Once you've submitted your issue, please add it to the content backlog project board: https://github.com/cfpb/design-system/projects/1***

**Comment by brandon-rusk** [comment]
Added second PR that removes duplicate code from CFGov

https://github.com/cfpb/consumerfinance.gov/pull/6749

**Comment by sonnakim** [comment]
@brandon-rusk We discussed this during sprint planning, and decided to scope this down to include only the regular email signup piece. Here are the tasks (please edit as needed)

- [ ] Remove the inset email from your [PR](https://github.com/cfpb/design-system/pull/1331) 
- [ ] @anselmbradford will create a separate issue to preserve comments and next steps from the original PR around the inset email sign up  
- [ ] Merge and release into the Design System   
- [ ] Brandon has PR to remove redundant code – update it with the changes in the latest design system release

**Comment by anselmbradford** [comment]
I think this can be closed. There's an example on https://cfpb.github.io/design-system/patterns/e-mail-signup-forms
