### ISSUE TITLE
Data visualization: Incorrect spec

### ISSUE THREAD

**Issue by huetingj** [cfpb/design-system#1042]
**Which page is this about?** 
Data visualization guidelines: https://cfpb.github.io/design-system/guidelines/data-visualization-guidelines

**What kind of issue is this?**
- Info incorrect 
- Content enhancement (Consider if there's a better way to present data viz specs.)

**Describe your issue** 
- The subtitle spec is incorrect. It should be paragraph style instead of H4. 

![Screen Shot 2020-08-06 at 2 23 01 PM](https://user-images.githubusercontent.com/10562530/89573153-2ae91100-d7f8-11ea-8477-d3de4069324f.jpg)

- We should think about the presentation format when we update this. Size of text on this static image is kind of hard to read. Would it work better to have specs in a list format? If we do decide to keep it as a static image, I think we'll need to recreate the image from scratch because I'm not sure if/where these design files currently exist.

**Comment by huetingj** [comment]
Two examples where the subtitle is handled correctly as paragraph text:
- https://www.consumerfinance.gov/data-research/mortgage-performance-trends/mortgages-90-or-more-days-delinquent/
- https://www.consumerfinance.gov/data-research/consumer-credit-trends/auto-loans/origination-activity/

Also, formatting idea from Natalia: maybe instead of a static image with the specs, we could present specs in a live-coded example.

**Comment by ielerol** [comment]
Updating the listed text specs should be pretty easy. I want to think a little more about how to change the images. It looks like the page lists specs for charts that can appear in various different places, with a lot of overlap in the basic styling that makes it difficult to find the few specs that are different in the various contexts. I think I can restructure those lists a bit to make them clearer, and change the way images are used to illustrate those examples to be more useful.

**Comment by sonnakim** [comment]
The PR for this issue has been merged: https://github.com/cfpb/design-system/pull/1152 🙌
