### ISSUE TITLE
Table pattern: Update row header style

### ISSUE THREAD

**Issue by caheberer** [cfpb/design-system#1052]
**Is your feature request related to a problem? Please describe.**
All caps headers work well for 1 or 2 word labels, but most of our content does not fit this convention and is often longer, making the labels difficult to read. 

**Describe the solution you'd like**
We're proposing changing table headers from H5 to paragraph medium, sentence case, and top-aligning the baseline.

**New specs:**
Background: Gray-05 #F8F8F8
Font: Avenir Next Medium, sentence case
Font-color: Black #101820
Font-size: 16px
Top-align baseline

**Acceptance criteria**
- [ ] Design has reviewed and 👍 
- [ ] Specs updated on design system page
- [ ] Code snippet added to design system page

**Comment by anselmbradford** [comment]
PR --> https://github.com/cfpb/design-system/pull/1154
