### ISSUE TITLE
Table pattern: Update code to match stated specs of 10px padding for headers

### ISSUE THREAD

**Issue by caheberer** [cfpb/design-system#1053]
**Describe the bug**
Currently the `<th>` has 11.429px of padding and the `<td>` has 10px  

**Expected behavior**
Consistent padding of 10px

**Other notes**
We're also considering a 15px padding, but will review in code.

**Acceptance criteria**
- [ ] Design has reviewed and 👍 

If we change to 15px:
- [ ] Specs updated on design system page
- [ ] Code snippet added to design system page

**Comment by anselmbradford** [comment]
@caheberer Do you recall where you saw `<th>` having `11.429px` of padding? They appear to be correctly 10px on https://cfpb.github.io/design-system/components/tables

**Comment by caheberer** [comment]
Hmm. I was just recording for Natalia. @nataliafitzgerald can you clarify?

**Comment by stephanieosan** [comment]
bumping this for @nataliafitzgerald

**Comment by nataliafitzgerald2** [comment]
@stephanieosan - It does look like these are set to 10px. Perhaps it was fixed at some point. I will go ahead and close this issue.
