### ISSUE TITLE
Tables too wide for page width get cut off, instead of scrolling

### ISSUE THREAD

**Issue by caheberer** [cfpb/design-system#1058]
**Describe the bug**
Right now, if you make a table in Wagtail that's too wide, it just gets cut off. We have a [scrolling table pattern already defined](https://cfpb.github.io/design-system/components/tables#responsive-table-with-horizontal-scroll) but it's not getting applied by Wagtail. 

Additionally, scrolling is currently a table variation, would we want to make this part of the default pattern?

**Expected behavior**
Table scrolls when content is too large to fit on the page.

**Screenshots**
![Screen Shot 2020-09-02 at 11 00 31 AM](https://user-images.githubusercontent.com/4739887/92000580-a9f43b00-ed0b-11ea-94db-4543e6160363.png)

**Desktop (please complete the following information):**
 - OS: Mojave
 - Browser: Chrome
 - Version 84.0.4147.125

**Comment by contolini** [comment]
Did You Know™️? According to [crawl-cfgov](https://github.com/cfpb/crawl-cfgov), [iRegs](https://www.consumerfinance.gov/rules-policy/regulations/1026/l/) is the only part of our website that makes use of our scrolling table pattern.

Because horizontal scrolling only kicks in on smaller screens, IMHO it seems harmless to enable it by default, or to at least include a checkbox to enable it.

**Comment by sonnakim** [comment]
Brandon talked with OP, and they can't find which chart this issue affects, and it definitely doesn't seem like a pressing issue affecting the team. I'll mark this as low-priority for now and a possible candidate for closing.

**Comment by sonnakim** [comment]
Just want to confirm what Brandon found in the comment above. I've tested a couple pages with the scrolling tables class applied (like [this](https://www.consumerfinance.gov/rules-policy/regulations/1010/a/#624ee2f92dc2880a16e889c0b4621171e0ecd168ca11c3efbfd49dba) and [this](https://www.consumerfinance.gov/rules-policy/regulations/1024/e/#c775e941b332ed8e39a537b741293d299b6d9822d2809e42e9b1ceb1)), using a SauceLabs tunnel to test on both desktop with the specs OP noted, and on various configs on mobile. The table does scroll when the viewport is not big enough to contain its contents, so looks like this isn't an issue.  

I'm making a note (as part of Design System auditing work I'm doing) to discuss with the team whether either the scrolling or stacked table variation should be added as part of the default table pattern and how we should make that decision.
