### ISSUE TITLE
Featured Content Module: Default video image should be shrunk down slightly

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-system#1071]
## Bug

The cropping of the default video image is very tight when it appears in a featured content module at desktop sizes, or in the case of the tablet sizes it IS cropped.

### Current behavior

- Default video image is cropped in the featured content module at desktop and tablet sizes.

### Expected behavior

- Content area of the default video image would be shrunk down so it fits comfortably in view at most/all screen sizes.

### Steps to replicate behavior

1. Visit https://www.consumerfinance.gov/prepaid-rule/
2. Open the dev console settings and disable JavaScript.
3. Reload the page to show the default video image.
4. Resize the window and note that the image is cropped at certain sizes.

### Screenshots

<img width="801" alt="Screen Shot 2020-10-02 at 11 02 54 AM" src="https://user-images.githubusercontent.com/6433178/94938449-d7fda400-049e-11eb-926d-deb12c123a85.png">

**Comment by anselmbradford** [comment]
PR --> https://github.com/cfpb/consumerfinance.gov/pull/6284

**Comment by Scotchester** [comment]
@anselmbradford This ready to be closed?

**Comment by anselmbradford** [comment]
Yup!
