### ISSUE TITLE
Tags: spacing on mobile is off 

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-system#1072]
## Bug with tags style

The Related Reports links on 
https://www.consumerfinance.gov/data-research/research-reports/no-fear-act-annual-report-fiscal-year-2015/
look like this under 600px width:

<img width="696" alt="Screen Shot 2020-10-02 at 11 21 11 AM" src="https://user-images.githubusercontent.com/6433178/94940362-683ce880-04a1-11eb-8927-e0378e407051.png">

The spacing between a list of tags on mobile is off. 
This work should be done as a part of a larger effort to bring the tag pattern into the Design System (which also includes making the color teal instead of orange.)  

### Original notes from @anselmbradford 
The top border on the second link is being removed by https://github.com/cfpb/capital-framework/blob/master/packages/cf-typography/src/molecules/list.less#L54

This adjustment makes sense for `m-list__links`, but not with the modifications `m-related-metadata_topics` is adding.

This pattern should be included in CF (see https://github.com/cfpb/capital-framework/issues/947), released and updated here.

It should either be a modifier on `m-list`, or `m-related-metadata_topics` should be a parent container around the `m-list` (if this were added to CF that name likely would be generalized to something else).

**Comment by sonnakim** [comment]
Related: #2001
