### ISSUE TITLE
Expand markdown tables to full width

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/design-system#1136]
We want tables generated via markdown to expand to the full width of their container, otherwise we get squished-looking tables like on the [icon page](https://cfpb.github.io/design-system/foundation/iconography):

<img width="904" alt="6861fd80-c768-11ea-861b-f64ce5e648f1" src="https://user-images.githubusercontent.com/704760/103696999-4a35c700-4f6d-11eb-83e8-ba76272d1092.png">

However, we can't just `.m-variation table { width: 100% }` because it will affect our non markdown tables like the ones on the [table page](https://cfpb.github.io/design-system/components/tables).

Can we have jekyll apply a class to markdown tables when it generates the HTML pages?

**Comment by ascott1** [comment]
It's possible to add a custom class to a Markdown table in Jekyll. See [this gist](https://gist.github.com/tamouse/4204dddabb6b072b0242) for an example, using Kramdown. Would this be an acceptable solution?

**Comment by ascott1** [comment]
It looks like this was attempted. The Markdown contains `{: class="icon-table"}` markup after each table, but the class isn't being applied.
