### ISSUE TITLE
Banners: Add global banner variation

### ISSUE THREAD

**Issue by contolini** [cfpb/design-system#1144]
**Which page is this about?** 
https://cfpb.github.io/design-system/components/banners

**What kind of issue is this?**
Add one or more of the issue labels below to the right-hand sidebar AND issue title. 
(We strongly encourage you to make content changes yourself where possible!)
- [ ] Info incorrect 
- [ ] Content enhancement (e.g. confusing or redundant content, small content items need to be added, etc.) 
- [x] Needs content written (page is missing key information, e.g. use cases)
- [x] Needs code snippet
- [ ] Overhaul page (page needs large-scale content rewriting and restructuring) 
- [ ] Something else (please explain)

**Describe your issue** 
There is a version of our banner component that cf.gov uses that sits across the entire top of the screen, here's an example:

<img width="1670" alt="Screen Shot 2021-01-12 at 11 31 20 AM" src="https://user-images.githubusercontent.com/1060248/104343380-de51e200-54c9-11eb-9304-e68417f27e27.png">

In the code, it's a molecule called `m-global-banner`, the CSS for it is [here](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/css/molecules/global-banner.less).

That CSS should be migrated to the DS and the consumerfinance.gov codebase should import it, the same way it imports the generic [banner organism](https://github.com/cfpb/design-system/blob/main/packages/cfpb-notifications/src/organisms/banner.less).
 
**Size this request (1=tiny, 5=enormous)**
3

**Comment by anselmbradford** [comment]
cfgov PR https://github.com/cfpb/consumerfinance.gov/pull/7745

**Comment by sonnakim** [comment]
This was added to the page (the URL was changed to https://cfpb.github.io/design-system/components/banner-notification). The CSS was updated from `m-global-banner` to `o-banner` to pull from the Design System version, and redundant CSS removed from cfgov.
