### ISSUE TITLE
Markdown tables aren't rendering properly

### ISSUE THREAD

**Issue by sonnakim** [cfpb/design-system#1239]
**Describe the bug**
Markdown tables are getting squished, so that columns are super narrow and images are too small to see:
![image](https://user-images.githubusercontent.com/9451445/120675070-bfe18880-c462-11eb-9917-c24b01a8f7c7.png)

This is especially bad for the pages section, which uses images in tables to show differences in page layouts. Example on the [landing page](https://cfpb.github.io/design-system/pages/landing-pages).  

**Expected behavior**
Unsquished tables

**Notes**
Browsers: This bug appears on Chrome 91 but not Chrome 90, not the latest Safari.

**Comment by contolini** [comment]
Note: This issue surfaced with Chrome >= 91 when its [table width calculations](https://chromium-review.googlesource.com/c/chromium/src/+/2875946) were fixed.

**Comment by sonnakim** [comment]
🙌  thanks @contolini !

**Comment by sonnakim** [comment]
The types markdown tables look wonderfully roomy and de-squished now  👏  but it seems markdown tables in other sections of the page are still in need of unsquishing: see e.g. [this markdown table in a behavior section](https://cfpb.github.io/design-system/pages/landing-pages#behavior), [another markdown table in a behavior section](https://cfpb.github.io/design-system/patterns/featured-content-module#behavior), and [this table in a guidelines section](https://cfpb.github.io/design-system/foundation/photography#guidelines). @contolini @anselmbradford
