### ISSUE TITLE
Add 50/50 Hero

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/design-system#1275]
***For content requests, use the content issue template instead.***
 
- Reconcile new 50/50 hero with jumbo hero (only on homepage and https://www.consumerfinance.gov/start-small-save-up/)
  - Decide if we want both or just one.
- Add 50/50 hero and/or jumbo hero to heros page https://cfpb.github.io/design-system/patterns/heroes

**Comment by Scotchester** [comment]
What does this look like? Seems like an oxymoron 😆

**Comment by anselmbradford** [comment]
👋 hi @Scotchester !

It'll look like https://www.consumerfinance.gov/start-small-save-up/ but the text and image will divide the space 50/50.

**Comment by Scotchester** [comment]
Ohhhh, hahah, gotcha. I was thinking a half-width hero.

**Comment by sonnakim** [comment]
These were added to https://cfpb.github.io/design-system/patterns/heroes
