### ISSUE TITLE
Add expandable facet pattern

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/design-system#1292]
https://www.consumerfinance.gov/consumer-tools/educator-tools/youth-financial-education/teach/activities/ has some sidebar expandable patterns that we don't capture in the design system. This is requiring some customizations in https://github.com/cfpb/consumerfinance.gov/pull/6660

**Comment by anselmbradford** [comment]
CCDB has a similar pattern https://www.consumerfinance.gov/data-research/consumer-complaints/search/?dataNormalization=None&dateRange=3y&date_received_max=2021-09-14&date_received_min=2018-09-14&searchField=all&tab=Map

**Comment by sonnakim** [comment]
There are also some (simpler) sidebar expandable patterns on [iRegs](https://www.consumerfinance.gov/rules-policy/regulations/1002/) and the [prepaid database](https://www.consumerfinance.gov/data-research/prepaid-accounts/search-agreements/)

**Comment by anselmbradford** [comment]
> There are also some (simpler) sidebar expandable patterns on iRegs and the prepaid database

Mmm yes regs does its own customizing https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/apps/regulations3k/css/reg-search.less#L34-L62

These similar patterns seem to be more of an argument to include the patterns in the DS.

**Comment by anselmbradford** [comment]
Work on this has been drafted up in https://github.com/cfpb/design-system/pull/1628, however, TDP contains some unusual behavior where checking all children of a checkbox does not check the parent, and also options are dynamically added and removed in a seemingly buggy fashion.

**Comment by sonnakim** [comment]
This was a pattern in TDP but we no longer have it. If we do want this as a component in the future, we should wait till we're further ensconced in web component land.
