### ISSUE TITLE
Design System docs pages page doesn't have indented links

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/design-system#1294]
It's weird that https://cfpb.github.io/design-system/pages/ doesn't have indented links, unlike every other section:

<img width="349" alt="Screen Shot 2021-09-13 at 3 25 08 PM" src="https://user-images.githubusercontent.com/704760/133144373-4df7f548-dd14-4dad-893f-af68f9ec9872.png">

**Comment by BrewCityBoy** [comment]
Second level nav was missing in the yml file, which then neglects to add the "ds-nav-2" class. There is a PR (1673) out for this change.

https://github.com/cfpb/design-system/pull/1673
