### ISSUE TITLE
Redirect to new accessibility page using Netlify

### ISSUE THREAD

**Issue by brandon-rusk** [cfpb/design-system#1324]
Redirect https://cfpb.github.io/design-system/guidelines/accessibility 

to 

https://cfpb.github.io/design-system/guidelines/accessibility-principles

Use Netlify redirect for this issue.

**Comment by brandon-rusk** [comment]
Ended up having to use Jekyll plugin for redirect as Netlify would not work

**Comment by sonnakim** [comment]
@brandon-rusk Ack, I just found another link that needs redirecting: https://cfpb.github.io/design-system/accessibility to https://cfpb.github.io/design-system/guidelines/accessibility-principles . Would it be a lot of effort to redirect this?

**Comment by brandon-rusk** [comment]
> @brandon-rusk Ack, I just found another link that needs redirecting: https://cfpb.github.io/design-system/accessibility to https://cfpb.github.io/design-system/guidelines/accessibility-principles . Would it be a lot of effort to create a redirect for this one?

@sonnakim, it's an easy change, but I'll have to open a new PR for it. Give me a few mins to fix it :)

**Comment by sonnakim** [comment]
@brandon-rusk Thank you!  🙏
