### ISSUE TITLE
Notifications colorize all icons contained within the notification, including external link icons

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/design-system#1351]
Inspect https://cfpb.github.io/design-system/components/notifications#information-base-notification-1  and add `m-notification__warning` to the notification with an external link icon and see that all icons get colorized. Only the notification main icon should be colorized.

<img width="365" alt="Screen Shot 2022-04-14 at 10 50 02 AM" src="https://user-images.githubusercontent.com/704760/163416970-7b29274c-a21d-470c-8ae9-109caf505b82.png">

**Comment by sonnakim** [comment]
Still an issue: e.g. https://www.consumerfinance.gov/about-us/blog/cfpb-proposes-prohibiting-mandatory-arbitration-clauses-deny-groups-consumers-their-day-court/
