### ISSUE TITLE
Examine media query helper mixin format

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/design-system#1353]
**Describe the bug**
The latest stylelint does not support the format of our media query mixin format of passing in an arbitrary block of rules. This should be researched as to whether we are writing these mixins correctly.

Ties into https://github.com/cfpb/design-system/issues/1265

**Comment by anselmbradford** [comment]
Search codebase for and remove `less/no-duplicate-variables` and `less/color-no-invalid-hex` and run `yarn run gulp lint` to see how stylelint stumbles on the media queries.

**Comment by anselmbradford** [comment]
Opened https://github.com/ssivanatarajan/stylelint-less/issues/6

**Comment by sonnakim** [comment]
@anselmbradford will revisit to see if this is still an issue once the Less to Sass conversion is done

**Comment by sonnakim** [comment]
@anselmbradford now the conversion is complete, do you mind checking to see if this is still an issue?

**Comment by anselmbradford** [comment]
Yup gone with the Sass conversion!
