### ISSUE TITLE
Update to work for Ruby 3.0.0 (Solution provided)

### ISSUE THREAD

**Issue by onelittlebecca** [cfpb/design-system#1385]
**Describe the bug**
Install will not run locally as described in readme file. Gets caught on machineevent gem install and fails with exit code 5

**To Reproduce**
1. Run yarn install with Ruby 3.x.x

**Expected behavior**
Install despite any dependency warnings so I could use locally

**Desktop (please complete the following information):**
 - OS: Catalina, then upgraded to Monterey (bc xCode)
 - Browser [e.g. chrome, safari]: Chrome
 - Ruby version: 3.0.0p0

**Additional context**
I got the install to run when I deleted the yarn.lock file and the node_modules folder. 
And then (and here is the key) installed eventmachine gem separately using 
`gem install eventmachine -- --with-openssl-dir=/usr/local/opt/openssl@1.1 `

This isn't an OS issue, as the installation works without supporting arguments with Ruby 2.7, but fails (unless you provide the location of openssl manually) with Ruby 3.0. There is an issue open with eventmachine, but <shrug>. Here is the link where I got the fix: [https://github.com/eventmachine/eventmachine/issues/932](https://github.com/eventmachine/eventmachine/issues/932)

Maybe add a note to your readme file if people are using ruby 3.0 on Big sur and Monterey

**Comment by sonnakim** [comment]
Thanks @onelittlebecca for the heads up! Pinging @chosak @brandon-rusk for awareness and to update our docs.

**Comment by anselmbradford** [comment]
Related to https://github.com/cfpb/design-system/issues/415

The overarching issue is that we should likely move off of jekyll and remove the Ruby dependency. This is the only repo we maintain that has a Ruby dependency.

**Comment by anselmbradford** [comment]
https://github.com/cfpb/design-system/pull/1475 added https://github.com/cfpb/design-system/tree/f351bbf93b65e4cd29500ad24340003e3f05fb62#running-the-documentation-website-locally
