### ISSUE TITLE
Email signup forms: `m-inset__email` modifier should be together with and modifying `m-inset`

### ISSUE THREAD

**Issue by sonnakim** [cfpb/design-system#1393]
**Describe the bug**
`m-inset__email` modifier should be together with and modifying `m-inset` 

**Details**
[https://github.com/cfpb/consumerfinance.gov/pull/4101](https://github.com/cfpb/consumerfinance.gov/pull/4101) added m-inset__email that appears in https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/jinja2/v1/_includes/organisms/full-width-text.html#L41. However, to be proper BEM this modifier should on the block m-inset, not on its own.

Also, this should probably be __50 or something (since it sets the width to 50% and adds some padding), so it fits with other modifiers like https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/css/molecules/inset.less#L84-L87

(Reported by @anselmbradford ; internal platform repo #4270)

**Comment by anselmbradford** [comment]
This was closed by https://github.com/cfpb/consumerfinance.gov/pull/8472, but perhaps we want to open a new email for the `__50` comment (now should be `--50` in post-new-bem-world).

**Comment by sonnakim** [comment]
@anselmbradford will close this issue and create a new one to cover this part of the issue:

> Also, this should probably be __50 or something (since it sets the width to 50% and adds some padding), so it fits with other modifiers like https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/css/molecules/inset.less#L84-L87

**Comment by anselmbradford** [comment]
@sonnakim Thinking about this further, I think I'm going to completely close this out for now. The other modifiers we have for `m-inset` include `.m-inset--170`, `.m-inset--270`, and `.m-inset--470`. I was thinking `.m-inset--50` here to fit with those. However, all the other modifiers refer to a specific pixel value (170px, 270px, etc), whereas the 50 is 50%, so it doesn't entirely fit with the others. Also, we only use `.m-inset--email` with the email signup inset in cfgov, so as it is currently having it named `--email` seems fine. I think at some point we may have used it for something that was not a signup email field, so in that case it was weirdly named, but we can cross that bridge again when we come to it.
