### ISSUE TITLE
GitHub actions: Lighthouse `set-output` should be migrated

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/design-system#1508]
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

https://github.com/cfpb/design-system/blob/main/.github/workflows/lighthouse.yml#L23

**Comment by sonnakim** [comment]
Eventually this setting is going to go away, but we should fix sooner rather than later. Will add to our internal backlog

**Comment by anselmbradford** [comment]
PR --> https://github.com/cfpb/design-system/pull/2067

**Comment by sonnakim** [comment]
Looks like this is done @anselmbradford ?
