### ISSUE TITLE
Lighthouse github action: migrate deprecated `set-output`

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/design-system#1517]
~The lighthouse GitHub action has been failing for awhile. It seems like we need to set a GitHub token in this repo's secrets (see https://github.com/treosh/lighthouse-ci-action/issues/60).~

Also, `set-output` will be retired on May 31, 2023 and needs to be migrated to environment files (see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

@chosak @wpears do we want to make these updates, or do we want to retire the lighthouse action as we talked about doing with https://github.com/cfpb/cfgov-lighthouse ?

**Comment by wpears** [comment]
I think this is failing due to https://cfpb.github.io/design-system/guidelines/frames-of-reference-mural-template?

**Comment by wpears** [comment]
(the iframe embed is causing the lighthouse issues, I just updated it to use a static image instead)

**Comment by anselmbradford** [comment]
I'm not sure that's related. The failure I see in the action is `No GitHub token set, skipping GitHub status check`. The instructions have either adding the Lighthouse GitHub app to repo or setting the `LHCI_GITHUB_TOKEN`, neither of which we have set.

**Comment by anselmbradford** [comment]
Hmm actually I see `GitHub accepted "failure" status for "lhci/url/design-system/guidelines/frames-of-reference-mural-template".` … is that what tipped you off?

**Comment by anselmbradford** [comment]
This PR handles the token issue, but the `set-output` still needs migrating --> https://github.com/cfpb/design-system/pull/1522

**Comment by chosak** [comment]
Isn't the use of `set-output` due to [this line](https://github.com/cfpb/design-system/blob/290cee62254e4a9abb47ad2d01ebc8e3396b4a57/.github/workflows/lighthouse.yml#L23) related to the Yarn cache dir?

**Comment by anselmbradford** [comment]
> Isn't the use of set-output due to [this line](https://github.com/cfpb/design-system/blob/290cee62254e4a9abb47ad2d01ebc8e3396b4a57/.github/workflows/lighthouse.yml#L23) related to the Yarn cache dir?

Yes should be that line (part of the Lighthouse GH action workflow, not lighthouse itself).

**Comment by anselmbradford** [comment]
Dupe of https://github.com/cfpb/design-system/issues/1508
