### ISSUE TITLE
Guidelines for sizing of icons that appear with text

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system#1675]
**Which page is this about?** 
#### Sections: 
  - [Icon with text](https://cfpb.github.io/design-system/foundation/iconography#icon-with-text-1)
  - [Content guidelines](https://cfpb.github.io/design-system/foundation/iconography#content-guidelines)

**What kind of issue is this?**
Add one or more of the issue labels below to the right-hand sidebar AND issue title. 
(We strongly encourage you to make content changes yourself where possible!)
- [x] Info incorrect 
- [x] Content enhancement (e.g. confusing or redundant content, small content items need to be added, etc.) 
- [x] Needs content written (page is missing key information, e.g. use cases)
- [x] Needs code snippet
- [x] Overhaul page (page needs large-scale content rewriting and restructuring) 
- [ ] Something else (please explain)

**Describe your issue** 
The Design System has two sets of sizing guidelines for icons that appear with text on the web. Neither of these guidelines match (or at least fully capture) what's happening with the code on the webpage. There is a section called "Content guidelines" that includes guidelines on the sizing and the color of icons with text. There is also a section called "Icons with text" that includes sizing guidelines but these guidelines don't indicate which specific heading levels they apply to. They use terms like "extra small" and "large." In web and in print we pair icons with specific headings and text. Our sizing guidelines should be specific. Additionally we should include examples as live code for all of the potential heading and text combinations. 
 
**Size this request (1=tiny, 5=enormous)**
I estimate a 4 for figuring out the sizing by heading and writing a plain language explanation of what is happening in the code and what the design and sizing intent is.  

**Add any additional background info as needed** 
- [Update all icons to have default 19px height; add new icons; revise some existing icons; add docs for devs](https://github.com/cfpb/design-system/pull/1234/files#diff-caab00bafa59ef123fda3f8cb27df5e961bae3e49734385010dbc283b87acd08)
- [Document new minicon standard](https://github.com/cfpb/design-manual/issues/551#issue)
- Make updates to the icon font - "Noun Project"

| Icons and text| Content guidelines|
|------------|------------|
|![Screen Shot 2023-07-19 at 12 39 48 PM](https://github.com/cfpb/design-system/assets/77348967/8f90ff0a-c504-4c06-9754-5c74af047f07)|![Screen Shot 2023-07-19 at 8 08 43 AM](https://github.com/cfpb/design-system/assets/77348967/37f55b77-05f8-4cd7-a383-87cd4b0a29f2)

***Thanks. Don't forget to add labels indicating issue type and size before submitting!***
***Once you've submitted your issue, please add it to the content backlog project board: https://github.com/cfpb/design-system/projects/1***

**Comment by natalia-fitzgerald** [comment]
I have now dug through a lot of documentation on this and would like to move forward with attempting to update the Design System documentation to better reflect the design intent and the implementation of this intent in the code. My focus is on the specs for the sizing of icons that appear inline with text(specifically on the web). 

In order to update the specs I would like to better understand the current state (and the history) of how we size icons that appear next to text on the website. These assumptions and guesses may not reflect the order in which these things happened but I wanted to try and piece this together in the hopes that someone may have some missing pieces to complete the picture.

## Assumptions

- The illustrator source files for the CFPB icon font were originally designed with art boards set to 1000 (w) x 1200 (h). 
- The SVG view box for icons was set to 1000 (w) x 1200 (h). (When exported, the illustrator art board dimensions are embedded into the SVG as the view box dimensions)
- When CSS was disabled icons would load very large. 

On August 23, 2019 the following comment was added to the Design System codebase: 
<img width="1116" alt="Screenshot 2023-07-25 at 3 39 48 PM" src="https://github.com/cfpb/design-system/assets/77348967/0d04d5b2-f7e8-427d-956f-bfa1bd00aaa5">

 - The vertical footprint of Avenir Next text at 16px (1em) renders with a height of 19px (h)
 - We came up with a calculation to scale the icons based on the text size (19/16 = 1.1875). 
 - We set a CSS class that sets the icons height to 1.1875em (cf-icon-svg)
 - The height was set to match the 19px “rendered canvas” of text set in Avenir Next

On May 19, 2021,  we standardized the height of all icons for the web. We set the art boards and SVG view box height to 19px. (Update all icons to have default 19px height; add new icons; revise some existing icons; add docs for devs #1234 (https://github.com/cfpb/design-system/pull/1234))

### Related issues:

#### Dec 15, 2017  Document new minion standard (https://github.com/cfpb/design-manual/issues/551)

> - Once it was determined that the icons would all live on Illustrator artboards of the same dimensions, [@jimmynotjim](https://github.com/jimmynotjim) and I needed to create a batchable action in Illustrator to remove whatever left and right whitespace exists in the files provided to us by the designers, so that when we actually display them on a webpage, that whitespace is not rendered.
> - As t[here](https://forums.adobe.com/message/5770361#5770361) is no simple command to do that kind of thing in Illustrator, we determined with some Googling that the easiest way to handle it would be to write an Illustrator script – a snippet of JavaScript that can be executed on an Illustrator document. We found some Adobe forum answers to get us started down this path, beginning with the example script found here. Once that was working, we began iterating on the script to get it to do what we wanted, primarily referring to the official Adobe llustrator CC 2017 Scripting Guide [[PDF](http://wwwimages.adobe.com/content/dam/acom/en/devnet/illustrator/pdf/AI_ScriptGd_2017.pdf)].
> - The final script we arrived at is documented in [#577 (comment)](https://github.com/cfpb/design-manual/issues/577#issuecomment-359943240)

### Notes about design intent:  Pulled from: https://github.com/cfpb/design-manual/issues/551#issuecomment-362435639

> #### Alignment
> 
> #### Circle icon alignment
> The overall position of a circle icon is centered on the cap height of Avenir Next. Inside the circle, icons are centered (optically).
> 
> #### Open icon alignment
> Outside of the circle, centering the icon often leaves it floating next to Avenir. To solve that, we started the grid on the baseline for more horizontal icons. Once an icon becomes taller than the cap height of Avenir, then it becomes centered on the cap height.

#### Sep 18, 2018 Huge SVG icons when CSS is disabled #863 (https://github.com/cfpb/capital-framework/issues/863) 

> “The new inline SVG icons look huge when CSS is disabled and makes it almost impossible to read the page.”

#### Aug 27, 2020  Make updates to the icon font - "Noun Project" #276 (https://github.cfpb.gov/CFPB/Consumer-Facing-Iteration/issues/276#issuecomment-285446) - 

> “I am currently working with Scott Cranfill on the web versions of the SVGs. We have come to certain conclusions regarding processing and necessary file considerations involved in export, which I will be documenting in detail. It's a very specific process and needs to be followed to a "T" in order to work properly. Now that we've almost gotten past the SVG coding, Scott is moving forward with testing the files by processing them through SVGO and using them "properly" in the dev environment.”

#### May 19, 2021  Update all icons to have default 19px height; add new icons; revise some existing icons; add docs for devs #1234 (https://github.com/cfpb/design-system/pull/1234) - May 19, 2021

> - “Previously, icons were very large in their native SVG format and had to be scaled down with CSS. Icons now have a more reasonable default size when viewed without SVG, and can be scaled up with CSS in the same way they were previously scaled down.”
> * Revises all icons to fix sizing issue describe above
> * Fixes the SVGO config file so that the process-icon-svgs script now works as desired.

 
## Current state: 
- The height of the the icon art boards in illustrator are set to 19px (h)
- When exported, the art board dimensions are embedded into the SVG as the view box dimensions 
- The height of the SVG view box is set to 19px (h)
- The art board/SVG view box for circle icons are set to 19 (w) x 17 (h). 
- The art board/SVG view box for open icons are set to 19 (h) and a variable width with a max of 17 (w)
- The art board/SVG view box includes padding/white space
- The path dimension (the actual icon footprint) is smaller

## Questions: 
- What was the original CSS goal for the sizing of the icons that appear inline with text? To scale up the size of the icons? 
- What is the current CSS goal for the sizing of the icons that appear inline with text? To scale down the size of the icons? 
- What is the current design intent for the sizing of circle icons that appear inline with text? Is there a size for each heading level? If yes, should we specify both the SVG view box dimensions and the path dimensions? 

## Assumptions about design intent
- The scaling of inline icons is based on the size of the parent heading element.
- The overall position of a circle icon is centered on the cap height of Avenir Next. Inside the circle, icons are centered (optically).
- Outside of the circle, centering the icon often leaves it floating next to Avenir. To solve that, we started the grid on the baseline for more horizontal icons. Once an icon becomes taller than the cap height of Avenir, then it becomes centered on the cap height.

@anselmbradford @contolini @Scotchester @chaisamantha @designlanguage

**Comment by natalia-fitzgerald** [comment]
### Current state for SVG icons:
This is my overview of the current state.
- The illustrator artboards for icons are set to 19px(h)
- When exported, the  illustrator artboard dimensions are embedded into the SVG as the viewbox dimensions 
- The height of the SVG viewbox is set to 19px(h) for all CFPB icons
- The  illustrator artboard/SVG viewbox for circle/round icons is set to 19px (w) x 17px (h) 
- The path for circle icons is 15.833px x 15.833px. 
   - There is 0.5835px of padding on each side (left and right). 
   - There is 1.58335px of padding on top and 1.58335px padding on top. 
- The  illustrator artboard/SVG viewbox for open icons is set to 19px (h) and a variable width with a max of 17px (w)
- The illustrator artboard/SVG view box includes padding/white space
- The path dimension (the actual icon footprint) is smaller than the  illustrator artboard/SVG viewbox
- The CSS code for icons is: .cf-icon-svg {height: 1.1875em; vertical-align: text-top; fill: currentcolor; max-width: 1em;}
- When the SVG icon sits outside of a parent element it defaults to 17px x 19px (path: 15.833 x 

### Design intent
These are my assumptions about the design intent (which I will pull from to write the guidelines)

- The scaling of inline SVG icons is relative to the size of the parent heading element.
- The overall position of a circle icon is centered on the cap height of Avenir Next. Inside the circle, icons are centered (optically).
- Outside of the circle, centering the icon often leaves it floating next to Avenir. To solve that, we started the grid on the baseline for more horizontal icons. Once an icon becomes taller than the cap height of Avenir, then it becomes centered on the cap height.
- The color of an icon should match the color of the text that it sits next to (in cases where the heading is the parent element the code will pull the color of the text and apply it to the icon)

**Comment by Scotchester** [comment]
Here are my answers to the open questions from my perspective and historical recollection (caveat: my memory may be faulty):

> #### Question 1:
> 
> What was the original CSS goal for the sizing of the icons that appear inline with text? To scale down the size of the icons? What exactly were were trying to solve for/accomplish?

Correct. Because the SVGs had 1000+ pixel artboards/viewboxes, CSS was required to scale them down to be appropriately sized in comparison to neighboring text.

> #### Question 2:
> 
> What is the current CSS goal for the sizing of the icons that appear inline with text? To scale up the size of the icons? What are we trying to solve for/accomplish?

The current end goal is the same – ensure the icon renders at the proportionate size to the text, regardless of the size of the text. Without the 1.1875em rule, you would have to specify exact icon sizes for each size of text that they could potentially be paired with, which would be quite unwieldy. Using the relative em units also ensures that the proportions remain correct if a user chooses to set a different default text size in their browser.

> #### Related to Question 1 and Question 2:
> 
> Did we once use the 16/19=1.875em calculation to SCALE DOWN the 1000 x 1200 SVG files and then later use the 16/19=1.875em calculation to SCALE UP the 19px high SVGs?

Yes, but to add a bit of nuance:
- For paragraph text that is set at 16px by default, the 1.1875em icon size results in the SVG rendering at exactly its native size (with a height of 19px).
- For anything larger than paragraphs, like headings, the 1.1875em icon size scales them up from their native height of 19px, maintaining the same visual proportion relative to the neighboring text size.

> #### Question 3:
> 
> What is the current design intent for the sizing of icons that appear inline with text? Is there a size for each heading level or should this be explained more in terms of being related to the height of the text on the webpage? I have some notes on design intent in this respect but no notes on design intent in terms of actual sizes.

I think the answers to the previous three questions essentially answered this, but to be specific: I don't recall there being a specific actual size specified for icons paired with text larger than 16px. We just let the calculation do its thing.

_Note: I feel like there may be a few one-off instances where icons paired with headings were intentionally made larger than the standard 1.1875em multiplier, but I can't point to any examples off the top of my head._

> #### Question 4:
> 
> What does this do: [process-icon-svgs](https://github.com/cfpb/design-system/blob/master/package.json#L36)?

It takes the SVG code that comes out of Illustrator and removes things that aren't needed for our use, which reduces the filesize, and it also adds two custom classes: `cf-icon-svg` and `cf-icon-svg__ICON-NAME`, which are used by our CSS to target the icons.

> #### Question 5:
> 
> What does this script do: ArtboardWidthToArt.jsx

This was a script that I developed to take Illustrator source file artboards, remove any left or right margin from them, and ensure that the vertical positioning of the path within the artboard was consistent. It may not be relevant anymore if the source files' artboards have already been updated to take these things into account.

**Comment by anselmbradford** [comment]
@Scotchester Do you recall why the `max-width` is `1em` and not `1.1875em`?

https://github.com/cfpb/design-system/blob/9aaa41e69c664680190495bb34ff63d51f30d883/packages/cfpb-icons/src/cfpb-icons.less#L47

**Comment by Scotchester** [comment]
> @Scotchester Do you recall why the `max-width` is `1em` and not `1.1875em`?
> 
> https://github.com/cfpb/design-system/blob/9aaa41e69c664680190495bb34ff63d51f30d883/packages/cfpb-icons/src/cfpb-icons.less#L47

No, I don't! I noticed that the other day and was curious, as well. For some reason, the SVGs were still rendering at 17px wide, according to the dev tools I was looking at, so I guess it should just be left alone!

**Comment by Scotchester** [comment]
If that rule was just for IE's benefit, though, maybe it can be removed entirely.

**Comment by natalia-fitzgerald** [comment]
@Scotchester
When I inspect in Chrome it looks like the max-width of 1em does make a round icon slightly smaller (round icons are all 17px (w) x 19px (h).

@anselmbradford Was that rule just for IE's benefit? If so can we remove it?

**Comment by natalia-fitzgerald** [comment]
## Update: 
I have now published an overhauled Iconography page which should bring us to the current state for how we style and implement icons at the CFPB. 

### [Design System - Iconography](https://cfpb.github.io/design-system/foundation/iconography)

#### Removed: 
- References to exact sizing for icons in web and print
- Section on spacing which is from the original Design Manual release and was out of date

#### Added: 
- Section at the top linking to the SVG icons on GitHub
- Design intent and guidelines for designers tasked with creating new icons or using existing icons 
  - The artboard (Illustrator artboard)
  - Relative size (across icons in library)
  - Alignment (with Avenir Next)
  - Color
  - Scale    
- Guidelines for web developers (and curious designers) about the icon artboard and how it relates to the SVG ViewBox as well as how we scale icons in relation to the text size and color icons in relation to the text color
- Updated "Behavior" section with current guidelines for development and links to the GitHub icon page, the Less file, etc.
  - Bonus: Updated the icon scaling explanation in `cfpb_icons.less` to include the 2021 update to SVG height x width (circa. 2021)
- Live code examples of icons with text for H2-H5 and paragraph
- (Recent addition in the past few weeks) Numerical icons 

#### Changed: 
- 50/50 content at the top of the page previously linked to the Noun Project and a download for the icon font. The latest release prioritizes the 2 primary use cases: SVG web icons and the CFPB icon font. 

#### Next steps: 
- Decide where to link to the Noun Project (discuss with designers)
- Change "Icons with text" live code from 50/50 to a table (or leave as is)
- Do we need guidelines for print sizing or are the design intent and guidelines sufficient?
- Team review

I welcome (and would appreciate) any feedback or suggestions. And a special thanks to @anselmbradford and @meissadia for their collaboration on this update as well as special guest @Scotchester for his historical contributions and feedback.

**Comment by natalia-fitzgerald** [comment]
@anselmbradford @Scotchester 
I discussed the [max-width](https://github.com/cfpb/design-system/issues/1675#issuecomment-1666171197) with my team and we have decided to remove it. Once this is in production if we later identify a need for a specified max-width we can add it then.

**Comment by anselmbradford** [comment]
> I discussed the https://github.com/cfpb/design-system/issues/1675#issuecomment-1666171197 with my team and we have decided to remove it. Once this is in production if we later identify a need for a specified max-width we can add it then.

The original intent, as you no doubt know, is that we'd support IE much further back in regard to the CSS than in regard to JS. That said, I think if the patterns are kinda broken on legacy IE, but still readable, that's fine. So maybe we'll have unsightly gaps between icons and text in legacy IE. Given Microsoft was abandoned IE support, that seems good enough at this point.
