### ISSUE TITLE
[Bug] Fieldsets: Helper text in live code on fieldsets page does not match specs

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system#1709]
**Describe the bug**
Fieldsets page block and inline helper text in live code does not match specs
https://cfpb.github.io/design-system/components/fieldsets

**To Reproduce**
1. Go to 'https://cfpb.github.io/design-system/components/fieldsets'
2. Scroll to any live code example on the page
3. Inspect code for helper text
4. See error (Text is 500 instead of 400 and scales to 14px at mobile)

**Expected behavior**
Live code example should match Design System specs

**Task**
Looking for a dev to review the HTML live code block to determine what we need to correct to make this display properly. 

**Screenshots**

### Block helper text
| Desktop | Mobile |  
|------------| ------------|
|![Screenshot 2023-08-11 at 5 05 36 PM](https://github.com/cfpb/design-system/assets/77348967/73a916ba-c950-45ef-8c1f-9ae94194d923)|![Screenshot 2023-08-11 at 5 07 23 PM](https://github.com/cfpb/design-system/assets/77348967/6ec1dd68-9622-4384-9283-426cbc526f42)|

### Inline helper text
| Desktop | Mobile |  
|------------| ------------|
|<img width="837" alt="Screenshot 2023-08-14 at 1 03 24 PM" src="https://github.com/cfpb/design-system/assets/77348967/f150564a-df4f-44ad-9a93-1e4843584840">|<img width="360" alt="Screenshot 2023-08-14 at 1 04 21 PM" src="https://github.com/cfpb/design-system/assets/77348967/5ddbe037-eede-4e86-b394-9ab75cdd350a">|

**Additional context**
- The scaling issue at mobile is also captured in this issue: https://github.com/cfpb/design-system/issues/1700

**Comment by jenn-franklin** [comment]
@natalia-fitzgerald We don't have the design specs specified on the [Fieldsets DS page](https://cfpb.github.io/design-system/components/fieldsets). But when I look for a page on cf.gov that uses the "a-label_helper" class, I can see what you're saying—that the text is 400 weight and 16px size on desktop and mobile. Here's a [cf.gov example page](https://www.consumerfinance.gov/privacy/records-access/) showing this. So, that makes sense to me that these code examples in the DS should reflect what's actually in the cf.gov code. 

Back to the design specs not being listed on this DS page: I would say we should add them, but, based on our DS discovery work, I think we're in a potential state of flux regarding how we want to be documenting design specs moving forward—i.e. does it make sense to manually type design specs in the DS? Should we show CSS in a tab? Etc. So maybe we fix the live code example to reflect what's actually implemented on cf.gov but not manually type design specs on the DS page until we figure out our strategy for design specs moving forward?

**Comment by BrewCityBoy** [comment]
@natalia-fitzgerald @jenn-franklin  Ok, so I took a look at the HTML and CSS. Leaving everything as is, looks like the a-label_helper class sets the font size using the incorrect variable (size-vi = 14px). The font-weight is set to normal, but only inside of ".a-label__heading". Moving/updating a few CSS lines should do the trick, but I want to clarify; the helper text should be 16px on desktop and 14px on mobile correct?

**Comment by natalia-fitzgerald** [comment]
@BrewCityBoy 
Helper text should be 16px at both desktop and mobile. Also see: https://github.com/cfpb/design-system/issues/1712

**Comment by natalia-fitzgerald** [comment]
@BrewCityBoy - What is the status of this issue?

**Comment by BrewCityBoy** [comment]
> @BrewCityBoy - What is the status of this issue?

My apologies. I thought I added the branch to this issue for tracking. The helper text was fixed with [PR 1717](https://github.com/cfpb/design-system/pull/1717)
