### ISSUE TITLE
[Bug] Update date-picker to pull in placeholder text styling

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system#1713]
**Describe the bug**

The date-picker is not pulling in the placeholder text styling. The placeholder CSS here https://github.com/cfpb/design-system/blob/main/packages/cfpb-forms/src/atoms/text-input.less#L83 needs to be updated to apply to the date picker inputs.

**To Reproduce**
1. Go to '[/design-system/components/text-inputs#date-picker-inputs](https://cfpb.github.io/design-system/components/text-inputs#date-picker-inputs)'
2. Look at placeholder text color
3. Compare to [/design-system/components/helper-text#placeholder-text-1](https://cfpb.github.io/design-system/components/helper-text#placeholder-text-1)

**Expected behavior**
Date-picker placeholder text should match the styling of other placeholder text: /design-system/components/helper-text#placeholder-text-1

**Screenshots**
![Screenshot 2023-08-16 at 7 32 10 AM](https://github.com/cfpb/design-system/assets/77348967/471c8e60-feb9-4e37-bb0b-a1fede2ac4dd)

### Task:
Update placeholder CSS here https://github.com/cfpb/design-system/blob/main/packages/cfpb-forms/src/atoms/text-input.less#L83 to apply to the date picker inputs.

**Comment by anselmbradford** [comment]
The date input on https://cfpb.github.io/design-system/components/helper-text#placeholder-text-1 is actually not a date input field, it is set to `type="text"`, whereas https://cfpb.github.io/design-system/components/text-inputs#date-picker-inputs is a date input field (`type="date"`). For some reason the placeholder CSS here https://github.com/cfpb/design-system/blob/main/packages/cfpb-forms/src/atoms/text-input.less#L83 is not applying to the date inputs.

**Comment by natalia-fitzgerald** [comment]
Thanks @anselmbradford
To confirm, are these the next steps? 
- Set date input on https://cfpb.github.io/design-system/components/helper-text#placeholder-text-1 to `type="date"` instead of `type="text"`
- Update https://github.com/cfpb/design-system/blob/main/packages/cfpb-forms/src/atoms/text-input.less#L83 to apply to the placeholder date and the date picker

**Comment by anselmbradford** [comment]
> Set date input on https://cfpb.github.io/design-system/components/helper-text#placeholder-text-1 to type="date" instead of type="text"

The helper-text example maybe shouldn't have the date input field as an example, as the text says the placeholder text disappears when you type in it (which is true of a text input), but date inputs don't work that way.

> Update https://github.com/cfpb/design-system/blob/main/packages/cfpb-forms/src/atoms/text-input.less#L83 to apply to the placeholder date and the date picker

👍

**Comment by natalia-fitzgerald** [comment]
@anselmbradford 

Ok, that makes sense. I went ahead and removed the date input example from the placeholder text section. I thought about adding a generic text input placeholder example in addition to the email placeholder but decided against it - because I think we want to specifically urge users to use placeholder text for formatting text. The email address example is a good example of this.  
 
| Before | After |  
|------------| ------------|
|![Screenshot 2023-08-15 at 4 10 14 PM](https://github.com/cfpb/design-system/assets/77348967/746fd8ab-dff7-43c9-baa2-a50c36e247c5)|![Screenshot 2023-08-15 at 4 12 17 PM](https://github.com/cfpb/design-system/assets/77348967/7fcdebda-d2b4-4e59-b300-b981050d6c8e)|

The second part of this sounds like a dev task so I'll see who can pick that up. 
> Update https://github.com/cfpb/design-system/blob/main/packages/cfpb-forms/src/atoms/text-input.less#L83 to apply to the placeholder date and the date picker

**Comment by anselmbradford** [comment]
> Might you know why the "Implementation" tab is showing up in this section even though it has no content?

I don't see "implementation" on https://cfpb.github.io/design-system/components/helper-text#placeholder-text-1
