### ISSUE TITLE
Multiselect: On desktop drop-down options lose background fill 

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system#1728]
**Describe the bug**
When options are shown on desktop and the user scrolls through the options, the background fill is lost after the user scrolls past the first 3 options. 

Related issue: 
https://github.com/cfpb/design-system/issues/1164

**To Reproduce**
1. Visit https://www.consumerfinance.gov/about-us/blog/
2. Click on a multiselect.
3. Type something if the options don't show up.
4. Scroll down in the options past the first 3 and see that the background behind the options scroll away.

**Expected behavior**
Background should say opaque behind the options.

**Screenshots**

<img width="277" alt="Screenshot 2023-09-22 at 6 21 25 PM" src="https://github.com/cfpb/design-system/assets/77348967/d472b3bf-28a9-43a7-ab12-f4859f380cd7">
<img width="268" alt="Screenshot 2023-09-22 at 6 21 31 PM" src="https://github.com/cfpb/design-system/assets/77348967/4018accb-04ad-420b-8182-d3762b0b7332">

**Comment by anselmbradford** [comment]
I see this in Safari 16.6 (18615.3.12.11.2)
