### ISSUE TITLE
"Meta-header" component not set to receive mobile styling for H4

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system#1730]
**Describe the bug**
The "Meta-header" component is styled like an H4 but is not set to receive mobile styling for H4. Additionally, the component is called "Heading with icon" but seems to be more specific than that. It seems to specifically refer to either the "Meta-header" or a category within the meta-header? The heading for the component, the supporting copy, and the example bring up a lot of questions. I'd like to try to unpack this component so that I can update the documentation to better reflect exactly what's intended/referenced. 

Questions: 
- What specific component is being referenced in the Design System? 
  - Icon and H4
  - Icon and H4 plus pipe character and another icon and H4
  - Icon and H4 plus pipe character and another icon and H4 plus rule line and date

- What is considered the meta-header? 
  - Icon and H4 plus pipe character and another icon and H4 plus rule line and date?

## Design System content: 

![Screenshot 2023-09-26 at 3 34 02 PM](https://github.com/cfpb/design-system/assets/77348967/2fab0fdd-47ea-4bc4-8750-214ffa6145eb)
![Screenshot 2023-09-26 at 3 33 43 PM](https://github.com/cfpb/design-system/assets/77348967/0057aba1-e1a5-40dc-86ee-820076e60f9c)
![Screenshot 2023-09-26 at 3 33 47 PM](https://github.com/cfpb/design-system/assets/77348967/55163af5-959e-4fe7-a0d0-69dba6d28cc6)
![Screenshot 2023-09-26 at 3 33 53 PM](https://github.com/cfpb/design-system/assets/77348967/fdad09ee-4f45-48ec-ae87-15094e1a9cf0)

**To Reproduce**
1. Go to '[...](https://cfpb.github.io/design-system/foundation/headings#variations-1)'
2. Click on '[....](https://cfpb.github.io/design-system/foundation/headings#heading-with-icon)'
3. Read content for "Heading with icon" and read through HTML code snippet, implementation, and specs. 

**Expected behavior**
The component name, content, and example is specific and clear. And it receives the mobile styling. 

**Additional context**
Also appears: https://www.consumerfinance.gov/about-us/blog

@anselmbradford @jenn-franklin

**Comment by natalia-fitzgerald** [comment]
Update: @anselmbradford and I are working on fixing this bug.

**Comment by anselmbradford** [comment]
@natalia-fitzgerald Is this good to close?
