### ISSUE TITLE
Implement approved tag (pill) styling change

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system#1760]
In 2018 and 2020 we approved new styling for the pill component. This issue will implement this change in the Design System. 
- Approval: https://github.cfpb.gov/CFPB/hubcap/issues/90#issuecomment-266484

As part of the React component work we have already implemented this update. We would now like to push the change to the Design System. Satellite apps will have to be handled separately but the risk is low given that satellite apps are currently using different styling than the CFPB core website.  
 
**Describe the solution you'd like**

**Updated styling:**
- background-color: Teal/20
- border-color: Teal/100
- Add here

**Existing CSS for pills**

.o-multiselect_choices button {
    border: none;
    background: none;
    padding: 0;
    
.o-multiselect_choices li {
    display: inline-block;
    margin-right: 0.625em;
}

.o-multiselect_choices label {
    display: inline-block;
    padding: 2px 5px;
    padding-right: 1.78571429em;
    background-color: #5674a3;
    border-radius: 0.28571429em;
    color: #ffffff;
    cursor: pointer;
    font-size: 0.875em;
    position: relative;
}

.o-multiselect_choices label .cf-icon-svg {
position: absolute;
top: 2px;
right: 5px;
fill: #d3daeb;
}

.cf-icon-svg {
    height: 1.1875em;
    vertical-align: text-top;
    fill: currentcolor;

**Describe alternatives you've considered**
Full exploration here: https://github.cfpb.gov/CFPB/hubcap/issues/90#issuecomment-186734

Mock-up of approved implementation: 
![Screenshot 2023-10-02 at 2 06 35 PM](https://github.com/cfpb/design-system/assets/77348967/a709551c-5d82-42ba-bc2a-ddaff12b2f08)

**Comment by natalia-fitzgerald** [comment]
@jenn-franklin 
In reviewing the implementation here: https://github.cfpb.gov/CFPB/hubcap/issues/90#issuecomment-266484 I am realizing that a few things have changed since this component change was approved. So I decided to conduct a quick exploration so that we can nail things down.  

**Button styles:** 
- Height: 35px
- Background color: #0072ce (Pacific 100)
- Text: Avenir Next, Medium

**Existing pills** (live on the site): 
- Height: 22px
- Background color: #5674a3 (Navy 80)
- Text: Avenir Next, Regular or Medium (confirming now)

| Buttons | Pills|  
|------------| ------------|
|![Screenshot 2023-10-02 at 5 10 08 PM](https://github.com/cfpb/design-system/assets/77348967/658a3381-35ff-4411-8dbb-901cf8afe87e)|![Screenshot 2023-10-02 at 5 07 18 PM](https://github.com/cfpb/design-system/assets/77348967/a744e167-f822-4aaa-a065-c927475f6470)|


Notes:
1) We deprecated the "Microcopy" level of text. The pills in my original product design used the "Microcopy" text style contained in the Figma template. In order to stay true to the current state I have switched out the text in the pill styling to paragraph text. 
2) Buttons use Medium instead Regular text. In the mock-ups you can see that difference between the pill only designs (use Medium) and the example designs (use Regular).   
2) I noticed that our standard button with icon component uses a pipe character to separate the text from the icon. I wanted to be sure to explore this so that we can be certain we don't want to include it (generally I was trying to use as much from the core button styles as possible and to be deliberate about deviating). My specific use case uses a pipe character to separate 2 values within the label so it's unfortunate. But I think that we should think more broadly and globally about this component. 

| No pipe separator | Includes pipe separator|  
|------------| ------------|
|![No pipe](https://github.com/cfpb/design-system/assets/77348967/9ed0c098-02fb-48c5-8d18-25ec318c65eb)|![with pipe](https://github.com/cfpb/design-system/assets/77348967/a57032b7-a0d3-4ad7-bb2b-21ac4067260e)|

**Comment by anselmbradford** [comment]
> Height: 30px

Do we have guidance on touch target sizes? My understanding is they are recommends to be a minimum of 44px x 44px. (See https://github.com/material-components/material-components-android/issues/1279, for example.) Does that affect the height we want for the pills?

**Comment by natalia-fitzgerald** [comment]
@anselmbradford 
We do have some general guidance on touch target sizes within the large target checkbox and radio button pages: https://cfpb.github.io/design-system/components/checkboxes#behavior. 

What is the touch target for our standard button component? Standard buttons are 35px in height (visually) but do you know what we have the touch target size set to? Increasing the touch target for standard buttons is out of scope for this specific effort but I can open a separate issue if that is something you want to explore at this time. 

What I am suggesting here is an increase in the existing height of the pills from 22px to 30px. So the touch target would improve with this change, and we could look at extending the area that responds to user input outside of that visual area, if possible, to more closely align with the guidance.

**Comment by natalia-fitzgerald** [comment]
@anselmbradford @jenn-franklin 
I think what I'll do is start building this out using the following specs. Then we can see how it's working. 

**Specs for R1:** 
- Button height: 30px
- Touch target size (height) - 45px
- Background color: Team 20 (#d4e7e6) (see other states in mock-up)
- Text: Avenir Next, Regular, 16px
- Pipe separator (between icon and text): No

![pill-mock-up](https://github.com/cfpb/design-system/assets/77348967/246d9ae7-d33c-4b0e-8463-5f79ea62cfa3)

**Comment by jenn-franklin** [comment]
@natalia-fitzgerald Thanks for working on this and 👍 to all the specs you've chosen. Before reading your spec preferences, I had decided I preferred Teal 20, 30px height and no pipe separator. I was intrigued by Avenir Next Medium, but I don't think it's needed or particularly helpful. Regular weight is accessible and will help keep the design's footprint small. Great to seeing about making the touch target 45px. I think you can do that without going larger than 30px with the visual design. I agree with your comment that this should have less visual prominence than our button. 

I like the idea of calling this a tag. Seems like a fitting description to me, and I like aligning with USWDS's naming conventions when possible. It doesn't feel right to me to group this with buttons. It feels to me that it serves a different function and the interaction is kind of the reverse of a button's interaction in that when you click on a tag, you remove something vs. when you click on a button, you advance.

**Comment by natalia-fitzgerald** [comment]
@jenn-franklin 
Thanks for sharing your thoughts. That all makes sense and provides what I need to get started.  

So if we separate this into a "Tag" component do we need to we need to think bigger picture about what these other tag-related components should be and should be called? That is out of scope for my effort - and it might be that these particular components (3 and 4 below) only appear in the context of the filterable list/post preview. But it's good to be thinking about it/discussing it while we're exploring the tag component. 

My effort will address the styling of 1 and 2 below, the "Tag" component for the Multiselect component. In a separate effort we could update the post preview topic tag link to match the teal styling (so that these components seem more visually related (currently the tag/pill is Navy and the topic tag is Gold). 

1) Category tag - Multiselect/Filter (button)
2) Topic tag - Multiselect/Filter (button)
3) Meta header - Post preview (label)
4) Topic tag - Post preview (link)

|  Blog |
|------------| 
|![Frame 283](https://github.com/cfpb/design-system/assets/77348967/8f46ac29-3b43-40d1-96ab-694f4aa0ad22)|
