### ISSUE TITLE
Update button padding to match design specs

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system#1770]
**Describe the bug**
Button padding is 14px in code but 15px in the specs. 

**To Reproduce**
1. Go to https://cfpb.github.io/design-system/components/buttons#types-1
2. Click on 'Specs'
3. View padding in the specs (Left and right padding: 15px)
4. Inspect element in Chrome - See padding (Left and right padding: 14px)

**Expected behavior**
Padding in code and in the specs should match and be 15px. 

**Screenshots**
![Screenshot 2023-10-05 at 4 22 35 PM](https://github.com/cfpb/design-system/assets/77348967/deb7eff1-9444-4b13-82c6-4b182e28221d)
![Screenshot 2023-10-05 at 4 22 58 PM](https://github.com/cfpb/design-system/assets/77348967/5f1986e2-d4e8-4772-9b2a-db408b6cbb46)

**Additional context**
- Figma file already matches the correct specs

**Comment by sonnakim** [comment]
We removed design specs from the Design System for maintenance reasons; designers will now pull specs using Chrome Inspect or a similar tool.
