### ISSUE TITLE
Inconsistent margin in text introduction at desktop sizes

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system#1772]
**Describe the bug**
On the SBL team we're working on adding the Text introduction as a component to the React component library. We noticed that the space between the "Lead paragraph" and the "Descriptive paragraph" text doesn't follow our standard spacing that is based on units of 15px. 

### On desktop
- `<div class="lead-paragraph">` top-margin is set to 30px 
- `<div class="lead-paragraph">` bottom-margin is set to 18.33px (desktop) and 15px (mobile) 

### Existing implementation of component parts:

**Heading 1**
- Top-margin: 0 px (all screen widths)
- Bottom-margin: 15px (all screen widths)
- Drops to H2 at mobile

**Lead paragraph** 
- Top-margin: 30 px (all screen widths)
- Bottom-margin: 18.33px (desktop)
- Drops to custom H4 - Regular weight at mobile
- Bottom-margin: 15px (mobile)
- When it is the last element: 0px bottom-margin
- Sometimes implemented as a div and sometimes as a `<p>` class (styled with `<p>` class in DS and both `<p>` class and `<div>` on the website depending on the instance)

**Paragraph** 
- Top-margin: 0px (all screen widths)
- Bottom-margin: 15px (all screen widths)
- No style change at mobile
- When `<p>` is the last element bottom-margin: 0px

**[Cf.gov/DSR](http://cf.gov/DSR)**
- Block class applied to the wrapper element that encases the TextIntroduction's elements (h1, p.lead-paragraph, p, .list-link)
- Top-margin: 60px (all screen widths)
block_flush-top class (cf.gov) isFlushTop property (React)
 - Removes top-margin
- 45px space above Text introduction comes from (.u-layout-grid_main) and does not come from the text introduction's elements.

It doesn't appear the the Text introduction is a DS component. My understanding is that it is a "pattern" made up of component parts that are in the DS (Heading 1, Lead Paragraph, Paragraph (optional), Links (optional). Default spacing is inherited from the component parts (and spacing calculations), as well as div wrappers.  

Since we're building an actual component for the Text introduction in React we have the opportunity to apply the "intended spacing." Our plan is to move forward with implementing that but we will first have to confirm what that is.  If we would like to correct this on the Design System side we could create an actual text introduction component and define the specific spacing.

**To Reproduce**
1. Go to '(https://cfpb.github.io/design-system/patterns/text-introductions)' See image of component.
2. Click on '(https://www.consumerfinance.gov/compliance/supervisory-highlights/)'
3. See component on the website. 
4. Inspect lead paragraph text with Chrome inspector. See space: 18.33px

**Expected behavior**
Spacing between the lead paragraph and paragraph text should match our standard units. In this case the space should be 30px (or 15px) at desktop and 15px at mobile. 

**Style Source**
[[cfpb-core] base.less lines 312-323](https://github.com/cfpb/design-system/blob/main/packages/cfpb-core/src/base.less#L312-L323)

**Screenshots**
| consumerfinance.gov (live) | corrected spacing|  
|------------| ------------|
|![Screenshot 2023-10-06 at 4 47 40 PM](https://github.com/cfpb/design-system/assets/77348967/6d45f8f2-81f8-4a80-a791-369fc07afb37)|![Screenshot 2023-10-06 at 4 48 15 PM](https://github.com/cfpb/design-system/assets/77348967/e2fb644a-1625-4d8f-9258-736ba8339867)|

| consumerfinance.gov (live) | corrected spacing|  
|------------| ------------|
|![Screenshot 2023-10-06 at 4 50 11 PM](https://github.com/cfpb/design-system/assets/77348967/55628b8a-26aa-4fa3-b9fa-9e150339d3b5)|![Screenshot 2023-10-06 at 4 49 52 PM](https://github.com/cfpb/design-system/assets/77348967/094d918c-931d-492f-92a6-299850c32f67)|

Related issues:
https://github.com/cfpb/design-system/issues/950
https://github.com/cfpb/design-manual/issues/419
(related link: https://ajbush.github.io/design-manual/global-elements/text-introductions.html)

@anselmbradford @jenn-franklin @itsmedavep

**Comment by natalia-fitzgerald** [comment]
On the SBL team we are working on building the Text introduction component. Spacing on the consumerfinance.gov implementation does not align with our spacing guidelines as written. I have put together mock-ups of what is currently live on the site and options of adjustments we can make. 

### Text introduction (spacing mock-ups)
**A) This approach matches what is live on the site (30/18.33/15)** 
   - Space between Heading 1 and Lead paragraph: 30px 
     - Aligns with the [Heading followed by a heading](https://cfpb.github.io/design-system/foundation/fonts#heading-followed-by-a-heading) guidelines
     - Does not align with the [Hero implementation](https://cfpb.github.io/design-system/patterns/heroes#hero-with-illustration) where the space between Heading 1 and Lead paragraph is 15px
   - Space between Lead paragraph and Paragraph: 18.333px
     - This spacing unit is a departure and does not follow our standard units of measure
   - Space between Paragraph and Call to action link: 15px
     - This is the standard space between a Paragraph and Call to action links

**B) 15px between component parts (15/15/15)**
   - Space between Heading 1 and Lead paragraph: 15px
     - This aligns with the approach we take on Hero graphics for this combination
   - Space between Lead paragraph and Paragraph: 15px
   - Space between Paragraph and Call to action link: 15px
     - This is the standard space between a Paragraph and Call to action links

**C) Mixed approach (30/30/15)**
   - Space between Heading 1 and Lead paragraph: 30px
     - Aligns with the [Heading followed by a heading](https://cfpb.github.io/design-system/foundation/fonts#heading-followed-by-a-heading) guidelines
   - Space between Lead paragraph and Paragraph: 30px
   - Space between Paragraph and Call to action link: 15px 
     - This is the standard space between a Paragraph and Call to action links
     
**D) 30px between component parts (30/30/30)**
   - Space between Heading 1 and Lead paragraph: 30px
     - Aligns with the [Heading followed by a heading](https://cfpb.github.io/design-system/foundation/fonts#heading-followed-by-a-heading) guidelines
   - Space between Lead paragraph and Paragraph: 30px
   - Space between Paragraph and Call to action link: 30px 
     - Typically this would be 15px. I changed it here to provide balance with the spacing for the rest of the component. It kind of depends whether we see the Call to action link as a part of the Text introduction as a whole or belonging to the Paragraph text specifically. If the Call to action link follows the Lead paragraph text it will get the 30px of space. 
          

| A) Existing spacing on consumerfinance.gov (30/18.33/15) | B) 15px between component parts (15/15/15)|  
|------------| ------------|
|![30:18 33:15](https://github.com/cfpb/design-system/assets/77348967/b36472b3-0e26-48ef-b0fd-cda3463a1c08)|![15:15:15](https://github.com/cfpb/design-system/assets/77348967/4ebc6389-ce4e-48f8-9dfd-dcb3e5dd10c4)|

| C) Mixed approach (30/30/15) | C) 30px between component parts (30/30/30) |  
|------------| ------------|
|![30:30:15](https://github.com/cfpb/design-system/assets/77348967/2410e05e-5596-4d31-ade5-96717f25ed96)|![30:30:30](https://github.com/cfpb/design-system/assets/77348967/f54ff2e3-7a2c-4bee-bb85-cf6bd37e34c6)|

**Comment by natalia-fitzgerald** [comment]
@caheberer and I met this afternoon to go over the possible approaches to the spacing for the Text introduction component. We have not yet landed on our recommendation but we were able to remove some options from the mix and settle on a select few that are working best. 

### What we discussed

- Space between Heading 1 and Lead paragraph text 
  - In the context of the Text introduction, the Lead paragraph serves as subheading text rather than a heading that follows Heading 1. So it seems most fitting to apply 15px of space like we do for hero graphics instead of the [Heading followed by a heading](https://cfpb.github.io/design-system/foundation/fonts#heading-followed-by-a-heading) guidelines.
- Space between Lead paragraph and Paragraph text 
  - We will change the space between the lead paragraph and the paragraph text to one of our standard units. 
  - In the mock-ups below we settled on 15px. 
- Space between Paragraph and Call-to-action (standalone link)
  - In the context of the Text introduction, a Call-to-action (standalone link) will oftentimes serve as a primary action related to the page introduction. In these instances 30px makes sense. Where we land on this will depend on the rest of the spacing units (and common website combinations)
-  In the context of our website, the margin above the Text introduction is 45px
- The design intent for Text introduction specifies 60px of space after the Text introduction and before the rest of the page content. 

### These are the approaches we're considering 
1) **Incremental change (30/15/15):** This would be the most focused change we could make. We would change the space between the Lead paragraph and the Paragraph text to 15px. 
2) **Tighter spacing (15/15/15):** Adjust the space between the H1 and the Lead paragraph to reflect what we do on heroes (15px), use the standard space between Lead paragraph and Paragraph (15px), and use the standard spacing unit between paragraph and Call-to-action (standalone) link text.
3) **Tighter space with extra space for call-to-action link (standalone or list link) (15/15/30):** Adjust the space between the H1 and the Lead paragraph to reflect what we do on heroes (15px), use the standard spacing unit between Lead paragraph and Paragraph (15px), and include 30px of text between the paragraph and Call-to-action (standalone) link text in order to give this link more prominence - and relate it to the whole Text intro component as opposed to just the paragraph. 

| 1) Incremental change (30/15/15) | 2) Tighter spacing (15/15/15) | 3) Tighter spacing with extra space for CTA link (15/15/30) |
|------------| ------------|------------|
|![30/15/15](https://github.com/cfpb/design-system/assets/77348967/7054a443-6de6-44c1-b35b-f4c3c16ab720)|![15/15/15](https://github.com/cfpb/design-system/assets/77348967/1f5b08f3-725d-494a-b8c7-a2e3c93f59f6)|![15/15/30](https://github.com/cfpb/design-system/assets/77348967/d9774781-edc8-4b7a-ba22-99e2c92aeca5)|

As a next step we will consider the approaches we've included here. I will also look at some website examples as I compare the approaches. 

@ajbush @caheberer

**Comment by natalia-fitzgerald** [comment]
@caheberer 
As a first step we plan to build the Text introduction component and add it to the CFPB Design System. Initially it won't connect back to anything so we will have the opportunity to make adjustments if something needs to be tweaked. 

How about we go with Option 2 as a first step. I am torn about the space before the Call-to-action link and whether it should be 15px or 30px. I think it depends on the context which makes it a bit of a trade off. 15px is the standard spacing so I'm thinking we start there and see how it works. 

Option 2: 
- 45px space above H1
- 15px of space between all parts (H1, Lead paragraph, paragraph, CTA/list link)
![Screenshot 2023-10-13 at 5 07 30 PM](https://github.com/cfpb/design-system/assets/77348967/077e0b69-ebdb-45b3-9c21-f0b26f4e70e1)

**Comment by caheberer** [comment]
I think this looks great and agree the 15px spacing before the call-to-action link makes sense to start with.

**Comment by natalia-fitzgerald** [comment]
Thanks for your review! I have opened an issue to add the Text introduction to the DS. https://github.com/cfpb/design-system/issues/1783
