### ISSUE TITLE
Simplify references to list links versus call-to-action links

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system#1784]
**Which component is this about?** 
- Currently we reference the same _component_ under two different _names_ within the DS 
  - Both _components_ use the same HTML code snippets
- If there is no functional/code difference between the two link types we should update the content to remove the suggestion that these are two different components
  - On the "Lists" page the "Variations" section seems to be calling out modifications that can be made in code to show links in different ways. (She is referring to [link lists](https://cfpb.github.io/design-system/components/lists#link-list).) The guidelines are related to code modifications, not usage. 
  - On the "Links" page the "Call-to-action links" are written from a usage perspective. (She is referring to [this section](https://cfpb.github.io/design-system/components/links#call-to-action-links).)
- Should this component appear on both pages `<ul class="m-list m-list__links">`? If yes, how should we handle them? Are there any other similar instances of components with two names within the DS? 
- In the old days we called this type of link a "Standalone link" which made sense when paired with "Inline links." 
  - Now we have "Inline links" and "List links/Call-to-action links"
  - I think that "Call-to-action links" is outside of the norm in terms of the way we name components within the DS. 
- Perhaps we could use "List links" for the component name and include the usage guidelines within the supporting text? Call-to-action would then be a use case. BUT sometimes this component is not a part of a list.  
- Or, if we want to return to "Standalone links" we could include call-to-action and list link as a use case. 
  - This option maps well because a `m-list__links` `<ul class="m-list m-list__links">`can be a single link (standing alone) or more than one stacked link. 

### Call-to-action links
Call-to-action links are standalone links underneath paragraphs that highlight users’ next steps. They are medium weight and often used in unordered lists.
```
<ul class="m-list m-list__links">
    <li class="m-list_item">
        <a class="m-list_link" href="#">Sample call-to-action link</a>
    </li>
    <li class="m-list_item">
        <a class="m-list_link" href="#">Another sample call-to-action link</a>
    </li>
</ul>
```
- https://cfpb.github.io/design-system/components/links#call-to-action-links

### Link list
The link list modifier is intended to be used for lists where each item is a link. It converts to a finger-friendly link with a large tap area on smaller screens.
- https://cfpb.github.io/design-system/components/lists#link-list
```
<ul class="m-list m-list__links">
    <li class="m-list_item">
        <a class="m-list_link" href="#">Sample call-to-action link</a>
    </li>
    <li class="m-list_item">
        <a class="m-list_link" href="#">Another sample call-to-action link</a>
    </li>
</ul>
```
**What kind of issue is this?**
Add one or more of the issue labels below to the right-hand sidebar AND issue title. 
(We strongly encourage you to make content changes yourself where possible!)
- [ ] Info incorrect 
- [x] Content enhancement (e.g. confusing or redundant content, small content items need to be added, etc.) 
- [ ] Needs content written (page is missing key information, e.g. use cases)
- [ ] Needs code snippet
- [ ] Overhaul page (page needs large-scale content rewriting and restructuring) 
- [ ] Something else (please explain)

**Describe your issue** 
Keep this issue as small and specific as possible. Make clear what section of the page this issue is about.
 
**Size this request (1=tiny, 5=enormous)**
Add a sizing label to the right-hand sidebar.  

**Add any additional background info as needed** 
Make sure NOT to include internal links.

***Thanks. Don't forget to add labels indicating issue type and size before submitting!***
***Once you've submitted your issue, please add it to the content backlog project board: https://github.com/cfpb/design-system/projects/1***

@sonnakim for awareness

**Comment by natalia-fitzgerald** [comment]
We are moving toward verifying the "Links" component in the DSR. I have a few lingering content questions: 

**Easy content fixes I can make while I'm focused on this component:** 
- Should the "Standard link with icon" be "Link with icon"? The "Standard icon" section includes inline and list links (call-to-action links) but the example shows online an inline link. Should we show an example with an inline link and an example with a list link (call-to-action link(s)
https://cfpb.github.io/design-system/components/links#standard-link-with-icon

- Would you like me to update the page to show all link variations as Types? So one long section with the title "Types" that includes: 
  - Inline link
  - Call-to-action link
  - Destructive link
  - Standard link with icon (or link with icon)
  - Non-wrapping icon link
  - Jump link
  - Jump link with icon on the left 
  - Printed link
  
**More complicated question:** 
- Do we feel comfortable with referring to the same component as "Call-to-action" link on the Links page and "Link list" on the Lists page? The actual component code refers to this as `m-list__links`
- The catch is that this link can appear as a list or as a single list item

| Link list | Call-to-action link | 
|------------|------------|
|![Screenshot 2023-10-31 at 3 57 35 PM](https://github.com/cfpb/design-system/assets/77348967/819abbdc-b2aa-4ff1-8766-6b77883a4e11)|![Screenshot 2023-10-31 at 3 57 50 PM](https://github.com/cfpb/design-system/assets/77348967/4a507937-a492-49f6-b914-af5c74c90282)|

**Comment by sonnakim** [comment]
@natalia-fitzgerald no objections from me to what you propose— renaming to "Link with icon", calling that section "Types", or even renaming to "List links" (I think the documentation should be sufficient to clarify the different use cases). Happy to talk about "List links" though if you want to discuss any potential complications.

**Comment by natalia-fitzgerald** [comment]
The updated page is live so I'm closing this out: https://cfpb.github.io/design-system/components/links
