### ISSUE TITLE
Tagline, Global eyebrow, and Global eyebrow actions

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system#1797]
As we continue our work on building the React component library we are currently working on adding the Tagline and Global eyebrow components. 

Based on the SBL layouts we will need components that match: 
- `a-tagline`
- `m-global-eyebrow`
- `m-global-eyebrow_actions` 

### `a-tagline`
**Includes:** 
- USA flag plus the text
- Text: An official website of the United States government
- This component is included in the CFPB DS code AND as a pattern in the CFPB DS website/documentation

![Screenshot 2023-11-01 at 4 21 39 PM](https://github.com/cfpb/design-system/assets/77348967/fed9e7f1-2473-49d3-a643-68e5d12e2f07)
<img width="817" alt="Screenshot 2023-10-27 at 10 56 41 AM" src="https://github.com/cfpb/design-system/assets/77348967/20a5418d-5937-4912-b99e-832dfbced81f">

```
<div class="a-tagline">
    <span class="u-usa-flag"></span>
    <div class="a-tagline_text">
        An official website of the
        <span class="u-nowrap">United States government</span>
    </div>
</div>
```

### `m-global-eyebrow`
**Includes:** 
- USA flag
- Text: An official website of the United States government
- Gray background and bottom border
- This component appears on consumerfinance.gov and in the CFPB Design System code (and the UI of the actual DS site) but is not a component or pattern in the CFPB Design System documentation
<img width="900" alt="Screenshot 2023-10-27 at 10 50 40 AM" src="https://github.com/cfpb/design-system-react/assets/77348967/925d57ea-5072-4e50-b367-458429f3ddb7">

```
<div class="m-global-eyebrow">
    <div class="a-tagline">
        <span class="u-usa-flag"></span>
        <div>
            An official website of the
            <span class="u-nowrap">United States government</span>
        </div>
    </div>
</div>
```

```
.m-global-eyebrow {
  font-size: unit((12px / @base-font-size-px), em);
  padding-top: unit((@grid_gutter-width / 3 / @base-font-size-px), em);
  padding-bottom: unit((@grid_gutter-width / 3 / @base-font-size-px), em);
  background: @gray-5;
  border-bottom: 1px solid @gray-40;
}
```

## `m-global-eyebrow_actions`
**Includes:** 
- USA flag
- Text: An official website of the United States government text, plus the  plus the 
- Gray background and bottom border
- Languages links
- Submit a complaint phone number link
- This component appears on consumerfinance.gov but is not a component or pattern in the CFPB Design System documentation site.

![Screenshot 2023-11-01 at 4 21 57 PM](https://github.com/cfpb/design-system/assets/77348967/4b3a9621-e36d-4956-9ffd-6df6c8d4ce60)

## Component naming
In thinking about the naming of these components I took a look at a few other federal government design systems to see how they handle these _nearly_ identical components. 

### USWDS
Name: Banner
Name in code: usa-banner
- The equivalent of the a-tagline pieces are called `usa-banner__header-text`and "usa-banner__header-flag" in the code. 
https://designsystem.digital.gov/components/banner/
<img width="1102" alt="Screenshot 2023-10-27 at 11 19 20 AM" src="https://github.com/cfpb/design-system-react/assets/77348967/9caf4b4c-9476-48f1-ba0e-3a0cc5d318ee">

### Veteran's Affairs
Name: banner - official gov
Name in code: va-official-gov-banner
https://design.va.gov/components/banner/official-gov
<img width="932" alt="Screenshot 2023-10-27 at 11 19 35 AM" src="https://github.com/cfpb/design-system-react/assets/77348967/7f9649eb-8712-4c2b-877d-ced2b2b17a4e">

If we decide to add `.m-global-eyebrow` as a component to the CFPB DS website we may want to consider either giving it a more descriptive name in the code (alluding to the usa, or official gov, or gov, etc) or, at least, giving it a name like this in the documentation site (leaving the names in code as-is). 

## Questions: 
- Can we add `m-global-eyebrow` and `m-global-eyebrow_actions` to the CFPB Design System documentation site?
- Is there an opportunity to rename these components to: 
  - Better align with other government agencies that use a very similar component?
  - Assign a name that is more descriptive of the component?
  
@sonnakim for consultation and awareness

**Comment by natalia-fitzgerald** [comment]
I talked this over with @sonnakim and I have my next steps: 

- [ ] In "Components" section change "Banner notification" to "Banners"
- [ ] Write more general intro content that makes sense for the banner as a more general component (specifics will be found under Types)
- [ ] Add the global eyebrow as a Type (and rename to something more descriptive - Official gov banner or US gov banner)
- [ ] Figure out how to handle the actions variation (not really a Type but more of a variation on global eyebrow)
- [x] Move Taglines to the components section
  - Update: I moved Taglines to the components section. It is now in the "Alerts" subsection. This doesn't make sense but there wasn't a better subsection for it. I recommend that we remove all subsections and create a flat and alphabetized components section.

**Comment by natalia-fitzgerald** [comment]
@sonnakim 
I tried out the approach we outlined for the global eyebrow and it didn't work as well as I had hoped. Unfortunately, the global eyebrow is quite different than the other two banners that are currently housed in the "Banner notifications" component page.  

<img width="1229" alt="Screenshot 2023-11-03 at 10 29 58 PM" src="https://github.com/cfpb/design-system/assets/77348967/4cced8d5-5050-4e64-a108-ccba864f577c">
<img width="1212" alt="Screenshot 2023-11-03 at 10 30 07 PM" src="https://github.com/cfpb/design-system/assets/77348967/dbad0b3b-e51f-4830-9452-ffc1e7dfc1ec">

Another idea I have is to separate these into sections. I mocked up a flat structure for the left nav (just used the Chrome inspector). If we really did it, it would be alphabetized (not like what I show in the mock-up).
- Banner (notification)
- Banner (US gov)
<img width="1196" alt="Screenshot 2023-11-03 at 10 37 56 PM" src="https://github.com/cfpb/design-system/assets/77348967/c0b59ada-46bc-4f28-a912-1258bbf43ac1">
<img width="1317" alt="Screenshot 2023-11-03 at 10 46 39 PM" src="https://github.com/cfpb/design-system/assets/77348967/439a1a9e-39fc-4ccb-9b02-144b535f320b">


I think that at this point in time it would be quite helpful to remove the groupings from the components section (Alerts, Behavior, Form components, List and Tables). It is hard to come up with the right solution or even a stop gap solution while those are still in place. Is this something that we could prioritize? If not we will come up with a solution that makes sense within the React component library where we do have this flat structure and then do our best within the DS although that will mean having things like "Banner (US gov)" under "Alerts". 

Might you be open to removing the groupings at this point in time?

**Comment by sonnakim** [comment]
For the record, @natalia-fitzgerald and I chatted, and I'm fine with removing those groupings. I don't think it should be controversial, but we can always restore them if that's the case.

**Comment by sonnakim** [comment]
Natalia and I chatted about this — she will use "Components" as a placeholder for the eyebrow. I'm going to remove the subsections for Patterns as well, so there too, when I do that work, I'll update the eyebrows on those pages to "Patterns". We'll then decide whether it makes sense to have an eyebrow at all if there are no subsections. 

Also I agree with the approach mocked up in Option 1 for the titles of the banner pages 👍

**Comment by natalia-fitzgerald** [comment]
Hi @sonnakim 
I implemented the change to create the "Components" grouping. The catch is that this update isn't reaching the individual component pages because the eyebrows on those pages are hard coded. https://github.com/cfpb/design-system/pull/1396. So we'll have to handle that piece as a separate task. 

Here's a link showing the label change in the left navigation: 
https://cfpb.github.io/design-system/components/buttons

**Comment by sonnakim** [comment]
Thanks @natalia-fitzgerald. The eyebrows on individual component pages can be changed by [editing the markdown file directly](https://github.com/cfpb/design-system/blob/main/docs/pages/radio-buttons.md), rather than using the CMS. I've already done this on the [radio buttons](https://cfpb.github.io/design-system/components/radio-buttons) page — let me know if you'd like me to walk you through how that's done

**Comment by natalia-fitzgerald** [comment]
Hi @sonnakim 
How does this look to you as a start to the Banner (US gov) page? 
https://cfpb.github.io/design-system/admin/#/collections/pages/entries/banner-us-gov?ref=workflow 

If this looks good to you I'd like to go ahead and publish this very basic page. 

We can then determine whether we will add the `m-global-eyebrow_actions` component. On thee DSR side we plan to add a second component called "US gov banner (with links)". Generally my preference is that we have a parallel component in the CFPB DS for components we include in thee DSR. Particularly if that component is already used on consumerfinance.gov. Are there any complications or reasons we would not want to add the `m-global-eyebrow_actions` component to the DS?

**Comment by natalia-fitzgerald** [comment]
> Thanks @natalia-fitzgerald. The eyebrows on individual component pages can be changed by [editing the markdown file directly](https://github.com/cfpb/design-system/blob/main/docs/pages/radio-buttons.md), rather than using the CMS. I've already done this on the [radio buttons](https://cfpb.github.io/design-system/components/radio-buttons) page — let me know if you'd like me to walk you through how that's done

Thanks @sonnakim. I have made these updates the component pages on the DS. The eyebrow is now "Components" for all components pages.

**Comment by sonnakim** [comment]
Awesome, thanks!

**Comment by natalia-fitzgerald** [comment]
Here's where we landed. Closing because 
| Banner (US gov) | Taglines |
|------------|------------|
|<img width="1340" alt="Screenshot 2023-11-09 at 10 20 44 PM" src="https://github.com/cfpb/design-system/assets/77348967/fad0d5a9-34f8-44bc-b48c-0cd95eb54ffa">|<img width="1330" alt="Screenshot 2023-11-09 at 10 22 32 PM" src="https://github.com/cfpb/design-system/assets/77348967/9f28f656-2a33-497e-9d1a-7a629458c72b">|

All items here have been handled except for the question of the US gov banner (with links) (`m-global-eyebrow_actions`). We have not confirmed whether we need this component for the project so we will wait to addd it. 
https://github.com/cfpb/design-system/issues/1797#issuecomment-1790999149
