### ISSUE TITLE
Text Input - Hover - Define state styling (Success/Warning/Error status)

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system#1881]
As part of the React component library (and lending app) we are currently looking to nail down the state styling for text input (Error status).

### In the Design System we currently define the states as follows:
This is not visualized on the documentation page but is in the code. The hover state is Pacific while the other states are red. I am not sure whether this is intentional or a default style that was never customized for the error status. 
![Screenshot 2024-01-17 at 2 09 26 PM](https://github.com/cfpb/design-system/assets/77348967/b308848a-ab18-4cfe-abcd-6461d2899049)

### If we apply the same visual logic that we do for the "[destructive link](https://cfpb.github.io/design-system/components/links#destructive-link)" we could go with a dark red on hover. 

That would look like this. What do you think? 
![Screenshot 2024-01-17 at 3 15 54 PM](https://github.com/cfpb/design-system/assets/77348967/6996f109-6a2c-47e3-8f9c-3f3092e187ef)

### I cross-referenced USWDS and they don't appear to have a separate hover style for their text inputs. 

**Default**
![Screenshot 2024-01-17 at 4 11 50 PM](https://github.com/cfpb/design-system/assets/77348967/9f9cf1ef-f1c0-4381-8370-596a956ad74f)

**Hover (No change)**
The only change here is a cursor change. 
![Screenshot 2024-01-17 at 4 11 50 PM](https://github.com/cfpb/design-system/assets/77348967/9f9cf1ef-f1c0-4381-8370-596a956ad74f)

**Focus**
![Screenshot 2024-01-17 at 4 11 45 PM](https://github.com/cfpb/design-system/assets/77348967/59032389-03c0-4637-8b6b-054a1998f6f1)

@sonnakim for guidance

**Comment by sonnakim** [comment]
@natalia-fitzgerald 👍 to adding a hover state for fields in error status, as shown above, and (as we discussed) to do likewise for checkboxes. @anselmbradford for awareness

**Comment by natalia-fitzgerald** [comment]
Ok, to confirm here are the colors for the hover states:

I don't have a use case for hover on success or warning in the work I'm doing but since the code currently defines these hover states as Pacific I recommend updating Success and Warning for the sake of consistent logic.  

**Success**
- Dark green: #1e9642

**Warning**
- Dark gold: #dc731c

**Error**
- Dark red: #b63014

**Comment by itsmedavep** [comment]
I have made these changes to the Figma DS library file on a branch here:

https://www.figma.com/file/V0QJU41AW9fesWLILNybld/branch/rnTYyS3Xot3Eag7pPdg8E5/CFPB-Design-System-1.5.0?type=design&node-id=387%3A220&mode=design&t=q3gqWy0ySj9HLBjs-1

@natalia-fitzgerald and @sonnakim 

If you like I can merge the branch and publish the changes to the file after a review. Just let me know.

**Comment by natalia-fitzgerald** [comment]
@itsmedavep 
I reviewed and the the Figma file looks good.

**Comment by itsmedavep** [comment]
I merged the changes and republished. TY everyone!

**Comment by billhimmelsbach** [comment]
I think this is completed @shindigira?
