### ISSUE TITLE
Clean up CSS cruft

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/design-system#1939]
**Describe the bug**

Post BEM conversion (see https://github.com/cfpb/design-system/pull/1919), here is some additional CSS that can be removed:

- ~~`a-tagline--xlarge`~~
- `content--2-1`
- ~~`content__wrapper--match-content` - this class is being created because `content__wrapper` extends `wrapper`, which defines `wrapper--match-content`.~~
- ~~`content__bleedbar`~~

Some refactoring:
- `o-table-wrapper--scrolling` should be updated to `o-table--scrolling`
- ~~`o-form--input-w-btn` to not be a modifier of `o-form` (see https://github.com/cfpb/design-system/pull/1933~~

**Comment by anselmbradford** [comment]
`content__bleedbar` removed in https://github.com/cfpb/design-system/pull/1960
`a-tagline--xlarge` removed in https://github.com/cfpb/design-system/pull/1954

**Comment by sonnakim** [comment]
@anselmbradford will update this issue

**Comment by anselmbradford** [comment]
`content__wrapper--match-content` removed in https://github.com/cfpb/design-system/pull/1997
`o-form--input-w-btn` removed in https://github.com/cfpb/design-system/pull/1979

**Comment by sonnakim** [comment]
@anselmbradford would you mind updating the status of this one?

**Comment by anselmbradford** [comment]
`o-table-wrapper--scrolling` renamed in https://github.com/cfpb/design-system/pull/2068
