### ISSUE TITLE
Fieldsets: Legend element is outside the fieldset

### ISSUE THREAD

**Issue by contolini** [cfpb/design-system#1961]
Our recommended [fieldset pattern](https://cfpb.github.io/design-system/components/fieldsets) involves a `<legend>` element outside the `<fieldset>` element. This is invalid, the legend needs to be a child of the fieldset.

See https://validator.w3.org/nu/?doc=https%3A%2F%2Fcfpb.github.io%2Fdesign-system%2Fcomponents%2Ffieldsets

<img width="1053" alt="image" src="https://github.com/cfpb/design-system/assets/1060248/9974b943-b329-4a8b-a3e5-9b58d4ebf68f">

**Comment by sonnakim** [comment]
We should fix this. There may be consequences to this depending on whether we depend on the current `<legend>` structure. I'll add it to our internal backlog.

**Comment by sonnakim** [comment]
This needs investigation to see if we are depending in some way on this broken pattern, and if we are, refactoring so that the pattern is both accessible and works as intended. @anselmbradford will look at this next sprint

**Comment by anselmbradford** [comment]
PR --> https://github.com/cfpb/design-system/pull/2009
