### ISSUE TITLE
cfpb-buttons: m-btn-group needs to add a row gap when buttons wrap

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/design-system#1971]
**Describe the bug**

If buttons appear in a `m-btn-group` and the buttons wrap (for example at small screen sizes), then the gap between the buttons is too tight.

**To Reproduce**
1. Go to https://cfpb.github.io/design-system/components/buttons
2. Inspect the page and edit the markup around groups of buttons to add a wrapper `m-btn-group` div. 
3. See at smaller screen sizes when the buttons wrap that they don't have a row gap between each other. Additionally, the wrapped button gets indented on a new line.

<img width="304" alt="Screenshot 2024-05-02 at 10 24 57 AM" src="https://github.com/cfpb/design-system/assets/704760/91267cab-8b87-4cfc-bc18-c2c34c0fb807">

@sonnakim for awareness

**Comment by sonnakim** [comment]
Next step: Check to see if there's a button group (more than 2 adjacent buttons) on cf.gov and if this bug is happening on that page @sonnakim

**Comment by sonnakim** [comment]
I checked using our internal cfgov scraper/crawler, and it looks like the only page where an instance of more than 2 buttons occurs on our site is [Before You Claim](https://www.consumerfinance.gov/consumer-tools/retirement/before-you-claim/). It looks fine? A screenshot of that page at 400px width (mobile) is below. 
<img width="392" alt="Screenshot 2024-06-27 at 3 15 19 PM" src="https://github.com/cfpb/design-system/assets/9451445/3862a442-8427-486d-a846-14fd67529eff">

@anselmbradford I'll close this, but feel free to reopen if there's anything else you'd want to check, or if you want this left open as a wont-fix.

**Comment by anselmbradford** [comment]
@sonnakim I'd leave it open, if you visit the DS on our phones, for example, it has that spaceless wrapping on the buttons page. We may not have enough buttons on the site to trigger this, but we could and the pattern should handle it. I'd recommend the [button-group CSS](https://github.com/cfpb/design-system/blob/main/packages/cfpb-buttons/src/molecules/button-groups.less) be updated to be flexbox with a 6px gap and ditch the margin-left technique that's currently being used.

**Comment by sonnakim** [comment]
Ans and I discussed this. We'd want to rewrite using Flexbox when moving to web components. Will put on hold for now.
