### ISSUE TITLE
Jinja detail being shown even when empty

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/design-system#1982]
**Describe the bug**
Visit the buttons page and click "SHOW DETAILS" and see there's a Jinja tab, which when clicked is empty.

**Comment by sonnakim** [comment]
This looks like it's fixed?  
<img width="816" alt="image" src="https://github.com/cfpb/design-system/assets/9451445/d6a27dbb-a4ab-43ed-956c-4630e97d1268">

@anselmbradford will reopen if he sees this again
