### ISSUE TITLE
Documentation: Integration instructions about unpkg.com are incomplete

### ISSUE THREAD

**Issue by chosak** [cfpb/design-system#1986]
**Describe the bug**
The [Integrating the Design System into your project](https://cfpb.github.io/design-system/getting-started/integrating-the-design-system-into-your-project) page instructs developers who want to download the compiled CSS and JS to

> [download the compiled Design System CSS and JavaScript from UNPKG](https://npmcdn.com/@cfpb/cfpb-design-system/)

and then

> Download the `cfpb-design-system.css` and `cfpb-design-system.js` files to your project and use standard <link> and <script> tags to include them.

The UNPKG link points [here](https://unpkg.com/browse/@cfpb/cfpb-design-system@1.2.0/), which contains both a `src` and `dist` directory. Presumably `dist` is what we want people to use; however [this doesn't contain](https://unpkg.com/browse/@cfpb/cfpb-design-system@1.2.0/dist/) a `cfpb-design-system.js`, only an `index.js`:

<img width="930" alt="image" src="https://github.com/cfpb/design-system/assets/654645/07d50e7b-95ab-4ce7-b296-1c4f92f75ab5">

The instructions should be updated to properly reference which files to download, perhaps mentioning why devs might also want to use the `.map` files. Additionally, should our dist JS file be named `cfpb-design-system.js` so that end users don't have to rename it?

@sonnakim for awareness

**Comment by sonnakim** [comment]
@anselmbradford will be consolidating files into one package as part of less to sass, so things will be imported differently then. As part of that work, he'll revisit this documentation and make changes as appropriate
