### ISSUE TITLE
Tags: Mobile styling is not rendering 

### ISSUE THREAD

**Issue by sonnakim** [cfpb/design-system#2001]
Topic tags [on this page ](https://www.consumerfinance.gov/data-research/research-reports/no-fear-act-annual-report-fiscal-year-2015/) are not receiving intended mobile styling. This looks like an accessibility issue as well as the links are too close together. 

<img width="373" alt="image" src="https://github.com/cfpb/design-system/assets/9451445/f98da1a9-a2b5-43af-a460-b4bec079f56c">

Ans thinks this may be dependent on the template used.  (ETA: Looks like this affects topic tags in the sidebar of doc detail pages.)

I'll bring this into our internal backlog and then we can see how widespread the issue may be

**Comment by anselmbradford** [comment]
PR --> https://github.com/cfpb/consumerfinance.gov/pull/8527

**Comment by sonnakim** [comment]
This bug is fixed. @anselmbradford is this ready to close, or anything else you'd like to track here?

**Comment by anselmbradford** [comment]
@sonnakim I'll close this specific issue, but next steps overall I think would be:

- Add this pattern to the design system (DS).
- Scrutinize the design further on whether we care about things like the gold bullet color not being accessible on white, what to do about wrapping of long topic tag text, etc.
- Merge the `m-related-metadata` and `m-tags` patterns used on cfgov into the one pattern developed in the DS.
