### ISSUE TITLE
Rebranding Capital Framework components

### ISSUE THREAD

**Issue by contolini** [cfpb/design-system#265]
With the migration of our [Capital Framework's code](https://github.com/cfpb/capital-framework) to this repository we have the option of renaming our CF components. Here are the options:

### 👀 Option 1 

Don't change anything. `cf-buttons` remains `cf-buttons`. `capital-framework` remains `capital-framework`.

### 🚀 Option 2 

Scope all the components to `@cfpb`. `cf-buttons` becomes `@cfpb/cf-buttons`. `capital-framework` becomes `@cfpb/capital-framework`.

### 🎉 Option 3  

Scope all the components to `@cfpb` and change the `cf-` prefix to `ds-`. `cf-buttons` becomes `@cfpb/ds-buttons`. `cf-typography` becomes `@cfpb/ds-typography`. `capital-framework` becomes `@cfpb/design-system`.

### ❤️ Option 4

Scope all the components to `@cfpb` and drop the `cf-` prefix. `cf-buttons` becomes `@cfpb/buttons`. `cf-typography` becomes `@cfpb/typography`. `capital-framework` becomes `@cfpb/design-system`.

-------------------------------

🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳
🗳 **Please vote by reacting to this post with the relevant above emoji** 🗳
🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳 🗳

-------------------------------

**Comment by Scotchester** [comment]
:ballot_box: :three:

**Comment by anselmbradford** [comment]
We went with `@cfpb/cfpb-`. See https://github.com/cfpb/design-system/commit/c5ed1312cfa258c407edf429feba33f869c5ff56
