### ISSUE TITLE
Breakpoint makes bottom links unviewable

### ISSUE THREAD

**Issue by doguin** [cfpb/design-system#353]
**Describe the bug**
When the browser is at the tablet size breakpoint I can't scroll down to access anything below the "Helper text" link [on this page.](https://cfpb.github.io/design-system/components/)

**To Reproduce**
1. Go to 'https://cfpb.github.io/design-system/components/'
2. Resize window to the tablet size.
3. Scroll down to the "helper text" link.

**Expected behavior**
I am able to access all the menu items/links at the desktop and mobile window sizes and should be able to do the same at the tablet size.

**Screenshots**

<img width="921" alt="Screen Shot 2019-09-17 at 10 40 27 AM" src="https://user-images.githubusercontent.com/6944937/65052299-49bc8b80-d938-11e9-9a3a-b28f0b0e46da.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave version 10.14.6
 - Browser Chrome 
 - Version 76.0.3809.132 (Official Build) (64-bit)

**Additional context**

**Comment by anselmbradford** [comment]
I can't reproduce this. @doguin please re-open if you are still experiencing this.
