### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/design-system#415]
**Describe the bug**

Provide instructions for installing `ruby` and `bundler` for those that want to install the project locally. Maybe in the contribution docs.

**Comment by stephanieosan** [comment]
This is for people who want to work on the Design System website? Or the code packages?

**Comment by anselmbradford** [comment]
The website. `ruby` and `bundler` are dependencies of `jekyll`, which runs the site.

**Comment by anselmbradford** [comment]
If `bundle` requires `sudo` access, `bundle install --path vendor/bundle` can be run to get around that.

**Comment by anselmbradford** [comment]
We have used https://www.11ty.dev/ in other repos (RAMPS internal repo for instance).
