### ISSUE TITLE
Overly broad GitHub permissions needed to edit

### ISSUE THREAD

**Issue by chosak** [cfpb/design-system#420]
Using the browser-based CMS to edit content requires granting what seem like overly broad permissions on GitHub.com. It asks for permissions on both public and private repositories,  saying that:

> This application will be able to read and write all public and private repository data. This includes the following:
>
> - Code
> - Issues
> - Pull requests
> - Wikis
> - Settings
> - Webhooks and services
> - Deploy keys
> - Collaboration invites

This feels overly broad; we shouldn't request all of these. It'd be nice to restrict these if possible.

This same issue is documented at https://github.com/netlify/netlify-cms/issues/1423 and seemingly fixed by https://github.com/netlify/netlify-cms/pull/2821. Do we need to pull this into [our fork of netlify-cms](https://github.com/cfpb/netlify-cms), push a new version of it [to npm](https://www.npmjs.com/package/@cfpb/netlify-cms), and update [the dependency](https://github.com/cfpb/design-system/blob/17d5c1e4bf60566cac1299184ddf88073386c5cc/docs/package.json#L33) used in this repo?

## Screenshots

![image](https://user-images.githubusercontent.com/654645/73402333-1234f700-42bb-11ea-9525-63db5f40aa7d.png)

**Comment by chosak** [comment]
I found [this](https://gist.github.com/contolini/3463e0ee85a5c6a29fdf1b75032c9444) useful gist from @contolini about how to upgrade our fork, but this will be a little tricky since one of the files we've modified (defaultPhrases.js) has been deleted as part of [this](https://github.com/netlify/netlify-cms/commit/096b067d4542c723630ded631fc9a4ba950732f3) commit. We'll need to figure out how to reimplement our customizations in the new version.

**Comment by chosak** [comment]
For posterity I'm not sure I agree this should be closed. Even with the change in #472 (thanks @contolini), this still requires read and write permission for all public repos:

![image](https://user-images.githubusercontent.com/654645/80828503-6057e000-8bb3-11ea-8664-970eecb4c2d6.png)

This is limited by how GitHub handles permissions: https://github.com/dear-github/dear-github/issues/113

**Comment by artrayd** [comment]
Middle of 2021, still relevant
