### ISSUE TITLE
`variation_specs` appears to be unused

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/design-system#421]
**Describe the bug**

`variation_specs` exists in the component templates (see [here](https://github.com/cfpb/design-system/search?q=variation_specs&unscoped_q=variation_specs)), for example [`bar-charts.md`](https://cfpb.github.io/design-system/components/bar-charts) has a `variation-specs` section that says "It must have data". but that doesn't appear on the live page because the [template doesn't include it](https://github.com/cfpb/design-system/blob/94a4ccaeabe12b710fe5231699ebaa5de5ab22ea/docs/_includes/variation-content.html#L75). (Reported via @chosak )

**Comment by contolini** [comment]
Yeah that's cruft, it can be removed. It was from before the specs got auto-generated from the CSV file.
