### ISSUE TITLE
Document processing icons

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/design-system#423]
How do we process the icons, for instance, to address https://github.com/cfpb/capital-framework/issues/863 ?

We have a [`process-icon-svgs`](https://github.com/cfpb/design-system/blob/master/package.json#L36) script in the `package.json` and there doesn't appear to be any public documentation on how/when this script should be used. It's used for processing the icons, but how.

**Comment by anselmbradford** [comment]
@Scotchester

**Comment by Scotchester** [comment]
Done in #1234 !
