### ISSUE TITLE
Committers who didn't contribute code changes show up in changelog

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/design-system#437]
**Describe the bug**

The changelog should describe code changes that have happened in each release of the design system to npm. The `yarn run changelog` command takes all the merged PRs with the magic lerna labels added (breaking, enhancement, bug, documentation, or internal) and adds them to the changelog file. It also aggregates all the committers together below the PR listing. However, the committers added are all committers to PRs, regardless of whether they have a magic label or not. Therefore, it may include committers who didn't actually commit to code change PRs listed in the changelog entries, which is misleading.

**Comment by cfarm** [comment]
*philosophical question* what if we take advantage of this bug to expand the definition of 'contributors?' after all, the purpose of the changelog is to describe the changes and who was responsible for them. I would consider reviewers of PRs to have knowledge of the change in addition to the person who actually committed the code.

**Comment by anselmbradford** [comment]
> I would consider reviewers of PRs to have knowledge of the change in addition to the person who actually committed the code.

So it isn't the reviewers that get included. It's all committers to PRs in the repo. However, we have two types of PRs. We have PRs that are changes to the [codebase packages](https://github.com/cfpb/design-system/tree/master/packages) and then PRs that are changes to the [docs](https://github.com/cfpb/design-system/pull/497). The packages are the only thing that gets released, so the changelog tracks those changes through the lerna "magic labels," but regardless of whether a PR has a magic label, the PR entry will be added or not, but the contributors across all PRs will be included (last I checked).

**Comment by contolini** [comment]
Related to https://github.com/lerna/lerna-changelog/issues/381

**Comment by sonnakim** [comment]
@anselmbradford Is this one still relevant?
