### ISSUE TITLE
Upgrade to Jekyll 4

### ISSUE THREAD

**Issue by chosak** [cfpb/design-system#465]
The documentation site currently uses Jekyll 3.8. Let's use [Jekyll 4](https://jekyllrb.com/news/2019/08/20/jekyll-4-0-0-released/) instead.

Upgrade documentation is [here](https://jekyllrb.com/docs/upgrading/3-to-4/).

**Comment by Scotchester** [comment]
We should wait on this until GitHub Pages itself is using Jekyll 4. [They're currently on 3.8.5](https://github.com/cfpb/design-system/issues/465).

**Comment by chosak** [comment]
Unfortunately based on [this issue](https://github.com/github/pages-gem/issues/651) it doesn't look like this is likely to happen any time soon. We could consider using GitHub Actions (something like [this](https://github.com/BryanSchuetz/jekyll-deploy-gh-pages)) to do the build ourselves and push it to the gh-pages branch. This would let us not only use Jekyll 4 but any other Jekyll plugins, not just ones [supported by GitHub](https://pages.github.com/versions/).

@anselmbradford @contolini would anything about such an approach be problematic with how things currently work with Netlify CMS? It seems like [we're already building the site](https://github.com/cfpb/design-system/blob/e4728cfc098ce15e630eb8a84d42d6eea03f3f2f/scripts/update-gh-pages.sh#L26) but then deleting it before we push.

**Comment by contolini** [comment]
> We could consider using GitHub Actions (something like this) to do the build ourselves and push it to the gh-pages branch.

We [do this already](https://github.com/cfpb/design-system/blob/master/.github/workflows/pages.yml) so we're good to use Jekyll 4. 👍
