### ISSUE TITLE
Create art boards and guides for images

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-system#857]
## User story
* As a designer contributing to the Design System, I want to have guidance on best practices for creating reference images for the Design System. 

---

### Background
From @designlanguage's previous version of this issue: 

A few notes about guidelines for adding images in the design system:

* The size of an image can't be set in the CMS, so the size its created at will be how it shows up in the design system.
* The width of an image is constrained by the max-width of the page (it doesn't matter how wide an image is, it will never be wider than the page width).
* There is no constraint on image height in the Design System, and we already see some unfriendly examples of this in our migrated images (templates pages).

#### Image height
To make sure an image doesn't get larger than the height of a page, I propose a max-height of 400px.

#### Text size
Along with that, any text that's contained in an image shouldn't be rendered smaller than 12px tall on the page.

**Comment by huetingj** [comment]
I've incorporated these notes into an Illustrator image creation template.
