### ISSUE TITLE
Add helper text to CMS for alt and title fields under uploaded images

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-system#872]
## User story
* As a design system contributor, I want to understand whether I should add alt text and titles to the images I'm uploading and if so, how I should write it so that I know what I'm contributing to the Design System is 508-compliant.

---

### Background
* We currently have fields for alt text and an image title for image uploads, but we don't have any guidance or helper text on those 
* Folks might not know why and how to write accessible ALT and title text for uploaded images. As a usability improvement, we could provide them with some short guidance through helper text for the fields.
* Also, one of our maintenance principles is to not customize the Netlify CMS, so that it's easier to upgrade and maintain. I'm not sure whether vanilla Netlify offers helper text for fields or not? 

### Work likely involved
* A little bit of technical discovery
* Write helper text 
* Implement it

**Comment by anselmbradford** [comment]
Likely cannot fix this because it uses the out-of-box image upload widget.

<img width="568" alt="Screen Shot 2021-08-19 at 3 18 48 PM" src="https://user-images.githubusercontent.com/704760/130130938-89af6ebd-b477-4a48-9681-19aabd860355.png">
