### ISSUE TITLE
Improve anchor links style

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-system#874]
## User story
As a design system user, I'd like to easily identify and get to different parts of the page's content so that I can quickly read what's most relevant for me. 

---

### Background 
*  As a part of our recent project, we did some minimal style tweaks to the design and location of the anchor/jump links on design system pages BUT we didn't make all of the tweaks we wanted to and the previous team also had ideas around styling. 
* Potential ideas for improvements
  * Grey background for jump links
  * Sticky jump links 

### Work likely involved
* Decide on any design improvements

**Comment by huetingj** [comment]
Mockup from the previous team:

![9fac2400-b9c7-11e9-8fa9-68b06b24ddb8](https://user-images.githubusercontent.com/10562530/94968297-a8ff2680-04ce-11eb-90af-966607f31a13.png)

Size: H5
Text color: Pacific
Hover/focus color: Dark Pacific
Active color: Navy
Visited color: N/A
Spacing between links: 40px
Background color: Gray 5

When you click on a jump link, it will become the active color. It will remain the active color while you are scrolling within that section. When you scroll out of a section, the link will return to Pacific, and the new section you've entered will turn Navy.

On mobile, don't have the anchor links as a sticky. Keep them after the introduction. Suggestion to add a sticky "Back to top" link/button.

**Comment by anselmbradford** [comment]
We're not using a sticky table of contents jump link section. As we discussed ages ago we no longer want them to be sticky.
