### ISSUE TITLE
Netlify: Disable auto-scroll by default in CMS

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-system#875]
From @contolini : 
See if we can disable this button by default
![image](https://user-images.githubusercontent.com/9451445/96291045-87fe0180-0fb5-11eb-97a1-cedcd61db833.png)

From @designlanguage :
This has been a problem in most tests because the auto-scroll happens in both panels only when you're scrolling in the editing pane.

If you scroll on the preview pane, then attempt to find a field in the edit pane, the preview will jump to a completely different location. Yes, the algorithm is inaccurate and doesn't correctly line up where you are in both panes, but it is also disruptive to navigating the CMS.

**Comment by anselmbradford** [comment]
This is not configurable in netlify CMS, so folks will have to manually disable it.

**Comment by sonnakim** [comment]
> If you scroll on the preview pane, then attempt to find a field in the edit pane, the preview will jump to a completely different location. Yes, the algorithm is inaccurate and doesn't correctly line up where you are in both panes, but it is also disruptive to navigating the CMS.

It looks like auto-scroll was fixed, or at least disabled. After editing in the edit pane, you _do_ have to scroll in the preview  pane to find an updated preview of what was just changed, but there's no jumping happening, so...I'm going to close this.
