### ISSUE TITLE
Notifications: Improve introduction content

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-system#879]
**Which page is this about?** 
[Notifications](https://cfpb.github.io/design-system/components/notifications)

**Describe your issue** 
* The notifications page introduction could use improvement. Ideally it would be in plain language, and a description of what a notification component is and why it exists. 

**Add any additional background info as needed** 
* Here's the current language: 
  * "This page describes notifications and form alerts, the latter which provide a light-touch alternative for inline form validation or feedback to a user’s input. The default (base) notification is also described; it is modified by scripting in production to update the state and message based on user input."
* Should be 1-3 sentences, and no more than 400 characters with spaces.

**Comment by niqjohnson** [comment]
I updated the notifications intro to:

>Notifications alert users to the state of a form or page. In forms, notifications can appear at the top of the form or in line with form fields and can highlight successful submissions, errors that need to be corrected, or details to know before submitting the form. When used on a page, notifications can call out important information about the content (including if the content is still loading).

Juuuuust under the wire at 399 characters! It's live now, so I'm closing this one (feel free to reopen if anyone think that needs more refinement).
