### ISSUE TITLE
Fieldsets: Is block helper text bold or regular?

### ISSUE THREAD

**Issue by sonnakim** [cfpb/design-system#891]
Block helper text is shown as [bolded when part of a legend](https://cfpb.github.io/design-system/components/fieldsets#fieldset-with-checkboxes). Block helper text is shown as [regular text when it's not part of a legend](https://cfpb.github.io/design-system/components/helper-text#block-helper-text-1). Is this intentional? If not, can this be fixed? 

**Expected behavior**
Block helper text styling should be consistent. 
 
I'm not sure if this is a content issue or a bug, but probably something a developer should investigate, so I've added the "help wanted: code" label.

**Comment by anselmbradford** [comment]
The legend gets set to `font-weight: 500` (as opposed to `400` or normal weight) by the parent `a-legend`. `a-legend` has a [`.h4()` mixin](https://github.com/cfpb/design-system/blob/main/packages/cfpb-forms/src/atoms/legend.less#L2), which sets a `.heading-4()` mixin that sets the weight [here](https://github.com/cfpb/design-system/blob/00948c3ac7e3425bb6c72c49ffd1d09d849223dd/packages/cfpb-core/src/base.less#L69). 

So either the bolding should be added to the non-legend version, or the heading mixin bolding should be negated in the legend version.

@huetingj Do you know whether these should both be bold or non-bold?

**Comment by anselmbradford** [comment]
Still need input from design on how this should appear. 

Is not bold on https://cfpb.github.io/design-system/components/helper-text
Is bold on https://cfpb.github.io/design-system/components/fieldsets

**Comment by BrewCityBoy** [comment]
Helper text should be 16px and 400 weight. This will be updated with [PR 1717](https://github.com/cfpb/design-system/pull/1717)

**Comment by anselmbradford** [comment]
1717 is merged
