### ISSUE TITLE
Lists: Add content about definitions

### ISSUE THREAD

**Issue by chosak** [cfpb/design-system#893]
**Which page is this about?** 
[Components > Lists](https://cfpb.github.io/design-system/components/lists)

**Describe your issue** 
This page lacks documentation about _lists of definitions_, for example the content on [this page](https://www.consumerfinance.gov/consumer-tools/auto-loans/answers/key-terms/). Consumerfinance.gov has several pages like this that use `<dl>`, `<dt>`, and `<dd>` tags for a list of definitions. This pattern is not currently documented in the design system.

**Comment by sonnakim** [comment]
Decided to close this, since there is no novel visual styling in how lists of definitions are rendered that would warrant their appearance in the Design System.
