### ISSUE TITLE
Range sliders: Needs code snippet

### ISSUE THREAD

**Issue by sonnakim** [cfpb/design-system#898]
**Which page is this about?** 
https://cfpb.github.io/design-system/components/range-sliders

**What kind of issue is this?**
Add one or more of the issue labels below to the right-hand sidebar AND issue title. 
(We strongly encourage you to make content changes yourself where possible!)
- [ ] Info incorrect 
- [ ] Content enhancement (e.g. confusing or redundant content, small content items need to be added, etc.) 
- [ ] Needs content written (page is missing key information, e.g. use cases)
- [x] Needs code snippet
- [ ] Overhaul page (page needs large-scale content rewriting and restructuring) 
- [ ] Something else (please explain)

**Describe your issue** 
Needs code snippet. Note range sliders are not in Capital Framework. 
**Size this request (1=tiny, 5=enormous)**
3?

**Add any additional background info as needed** 
Range sliders appear on the [Before you claim](https://www.consumerfinance.gov/consumer-tools/retirement/before-you-claim/) tool

***Thanks. Don't forget to add labels indicating issue type and size before submitting!***
***Once you've submitted your issue, please add it to the content backlog project board: https://github.com/cfpb/design-system/projects/1***

**Comment by anselmbradford** [comment]
An existing slider appears on https://www.consumerfinance.gov/owning-a-home/explore-rates/

**Comment by contolini** [comment]
> An existing slider appears on https://www.consumerfinance.gov/owning-a-home/explore-rates/

Hmmm and it's very different from the one on https://www.consumerfinance.gov/consumer-tools/retirement/before-you-claim/

**Comment by anselmbradford** [comment]
@sonnakim Do you have any guidance on reconciling the very different sliders on the Explore Rates tool and the Before You Claim tool? Do we document two slider styles or try to change one to fit the other?

**Comment by anselmbradford** [comment]
Code snippet added in https://github.com/cfpb/design-system/pull/1911
