### ISSUE TITLE
Links: Needs content written - add destructive links

### ISSUE THREAD

**Issue by sonnakim** [cfpb/design-system#904]
**Which page is this about?** 
https://cfpb.github.io/design-system/components/links

**What kind of issue is this?**
- [x] Needs content written (page is missing key information, e.g. use cases)

**Describe your issue** 
Add destructive links + use case. (An example of destructive links appears on the [buttons page](https://cfpb.github.io/design-system/components/buttons#destructive-actions), but we don't actually spec out and show the code for a destructive link on the link page itself.)
 
**Size this request (1=tiny, 5=enormous)**
2

**Comment by anselmbradford** [comment]
- Is there an example of a destructive link on the live site?

- What would the use case text say?

**Comment by anselmbradford** [comment]
> Is there an example of a destructive link on the live site?

Ah, "Clear filters" on https://www.consumerfinance.gov/about-us/blog/

**Comment by anselmbradford** [comment]
Added in https://github.com/cfpb/design-system/pull/1221

**Comment by sonnakim** [comment]
I've added specs for the destructive link
