### ISSUE TITLE
Color: Info incorrect - update color values

### ISSUE THREAD

**Issue by huetingj** [cfpb/design-system#926]
**Which page is this about?** 
Color: https://cfpb.github.io/design-system/foundation/color

**Describe your issue** 
- [x] The color values are outdated and need to be updated with the correct color values that Brenda put together in this doc: 
[CFPB Color Breakdown.txt](https://github.com/cfpb/design-system/files/4938905/CFPB.Color.Breakdown.txt)
- [x] When inputting the correct values, we need to make a note on the 10 values (i.e. Teal 10, Green 10, etc.) that a 10 value should only be used on the web and is too light for printing. 
- [x] FYI as part of this, we'll need a dev's help to create new swatches to show in the tables for the new color values. (We've already created Mid Dark Green, Navy 50, Gold 70 and Purple 50 to show in the Data viz palettes.)
*Additional idea from George: We could consider renaming the mid dark and dark swatches to numerical values. So something like Navy 110 for Mid dark Navy and Navy 120 for Dark Navy. This would allow us to add even darker swatches in the future if needed. <--- I'm leaning toward leaving as is now and making change in future if/when we develop more swatches and have a need.

**Comment by anselmbradford** [comment]
PR --> https://github.com/cfpb/design-system/pull/1049

**Comment by stephanieosan** [comment]
Is this fixed now? If so, close it @anselmbradford @huetingj !

**Comment by huetingj** [comment]
![giphy](https://user-images.githubusercontent.com/10562530/94955589-d04af900-04b8-11eb-8477-01c30048fcee.gif)
