### ISSUE TITLE
Filterable list page: Content enhancement - update wireframes to show filter

### ISSUE THREAD

**Issue by sonnakim** [cfpb/design-system#927]
**Which page is this about?** 
https://cfpb.github.io/design-system/pages/filterable-list-pages

**What kind of issue is this?**
Add one or more of the issue labels below to the right-hand sidebar AND issue title. 
(We strongly encourage you to make content changes yourself where possible!)

- Content enhancement (e.g. confusing or redundant content, small content items need to be added, etc.) 

**Describe your issue** 
Update the wireframes to show a filter? Otherwise, we're just showing the (unmodified) browse & sublanding wireframes. Or possibly remove the wireframes altogether and refer to the browse and sublanding pages.
 
**Size this request (1=tiny, 5=enormous)**
1

**Add any additional background info as needed** 
Make sure NOT to include internal links.

***Thanks. Don't forget to add labels indicating issue type and size before submitting!***
***Once you've submitted your issue, please add it to the content backlog project board: https://github.com/cfpb/design-system/projects/1***

**Comment by stephanieosan** [comment]
This could be a good contender for design system day, but we'd need to track down the wireframe source files.

**Comment by stephanieosan** [comment]
Alright, I updated the wireframes and merged it in! https://github.com/cfpb/design-system/pull/1149 
Annnnnd then realized I had an error in one of the images I created, so I'm in the process of trying to re-upload it.

**Comment by stephanieosan** [comment]
Okay, this should be fixed and done thanks to https://github.com/cfpb/design-system/pull/1151
