### ISSUE TITLE
Iconography: Info incorrect - need newest icon library

### ISSUE THREAD

**Issue by huetingj** [cfpb/design-system#929]
**Which page is this about?** 
Iconography: https://cfpb.github.io/design-system/foundation/iconography

**Describe your issue** 
This is not the newest version of the icon font. Need to update icons in the tables as well as the font file for download in the intro.

**Comment by anselmbradford** [comment]
It would be good to address the huge icons and how the icons are updated too. See 

https://github.com/cfpb/design-system/issues/423
https://github.com/cfpb/capital-framework/issues/863

**Comment by anselmbradford** [comment]
Should be done by https://github.com/cfpb/design-system/pull/1234 … reopen if not.
