### ISSUE TITLE
Atomic components: Info incorrect 

### ISSUE THREAD

**Issue by sonnakim** [cfpb/design-system#937]
**Which page is this about?** 
https://cfpb.github.io/design-system/development/atomic-components

**What kind of issue is this?**
- [x] Info incorrect 

**Describe your issue** 
Example code may be outdated
 
**Size this request (1=tiny, 5=enormous)**
1

**Comment by anselmbradford** [comment]
Should at very least have `AtomicComponent.extend` in place of `Molecule.extend`. The whole example should be scrutinized.
