### ISSUE TITLE
Buttons: Broken code snippet

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-system#944]
**Which page is this about?** 
[Buttons](https://cfpb.github.io/design-system/components/buttons)

**Describe your issue** 
The Animated icon in a button Variation doesn't have a button example that works. There is HTML code in there, but nothing is showing up. 

![Screen Shot 2020-07-20 at 10 43 44 AM](https://user-images.githubusercontent.com/6433178/87952219-90f33b80-ca77-11ea-840f-1032b192258a.png)

**Comment by anselmbradford** [comment]
I fixed this with https://github.com/cfpb/design-system/pull/953
The code snippet was just commented out with `<!-- … -->`. I'm not sure why. I just uncommented the code.

**Comment by stephanieosan** [comment]
Yay! 🎉
