### ISSUE TITLE
Filterable list control panel: Padding in the example image is incorrect

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-system#947]
**Which page is this about?** 
[Filterable list control panel](https://cfpb.github.io/design-system/patterns/filterable-list-control-panels)

**Describe your issue** 
Currently, rather than a live example, the page uses images to show the component. The second image is incorrect. It shows that there's 30px of padding between the form fields and the "apply filters" button, when it **should** be 15 px. This issue is about updating that image to show the correct padding (and therefore be accurate). 

**Add any additional background info as needed** 
* Not sure where the source file for this image is, it probably needs to be hacked in photoshop or reproduced. 
* Also, ideally this would be live code rather than an image. So, if this becomes live code #946 then this issue is no longer necessary.

**Comment by sonnakim** [comment]
Closing this - 30px is what's live on the site and looks like the appropriate amount of spacing
