### ISSUE TITLE
Info unit groups: Add 33/33/33 image + text components 

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-system#951]
**Which page is this about?** 
[Info unit groups](https://cfpb.github.io/design-system/patterns/info-unit-groups)

**Describe your issue** 
Need to add 33/33/33 image and text component to the page. We have the 33/33/33 example of text-only, but not one with images.

**Comment by sonnakim** [comment]
This has been added. @huetingj would you mind checking the specs when you get a chance? Want to make sure I've captured these correctly...

**Comment by huetingj** [comment]
@sonnakim The specs look good! I just made a few tweaks (such as removing references to isocons on the page) and republished. I think we can call this done. Thanks!

**Comment by sonnakim** [comment]
@huetingj thanks for checking! I'm realizing the placeholder images should be updated to remove the references to "isocon" as well. I can go ahead and do that.
![image](https://user-images.githubusercontent.com/9451445/97448434-07b99380-1907-11eb-915d-9091a7278eef.png)

**Comment by huetingj** [comment]
OH DANG UGH good catch thank you! Yes re: illustration or photography ... And thanks for updating. (I'm also happy to take care of this, just let me know.)

**Comment by huetingj** [comment]
Actually... I don't think that color combo is accessible... also may want to consider not using all caps H5. 🤔  Also, whatever we end up with, I should add to our DS template. So, yah. I'm happy to take this on. (Or if you already have, just send me your file and I'll add it to the template and such.)

**Comment by sonnakim** [comment]
Ooh yeah good call...although if we do a color correction and change to sentence case, this could be a bigger job, since we'd need to tweak all the visuals on this page....so maybe for now, I'll just upload what I have (the graphics now say "illustration or photograph") and then you can go ahead and change as you see fit? My file is a crappy Photoshop hack (couldn't find the original) so I would steer clear of it, but let me know if you'd still like to use it!

**Comment by huetingj** [comment]
Cool! That sounds like a good plan for wrapping up this specific github issue. And I'll take a gander at other FPO images in the DS to determine what we need in the template. And then we can update the images as we touch the various DS pages overtime (similar to updating breakpoint images overtime).

**Comment by sonnakim** [comment]
@huetingj cool, that sounds good!

**Comment by sonnakim** [comment]
Ok! 25/75 and 33/33/33 image placeholders have been updated to refer to "illustration or photograph". Closing this issue.
