### ISSUE TITLE
Info unit groups: Consider renaming the pattern

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-system#952]
**Which page is this about?** 
[Info unit groups](https://cfpb.github.io/design-system/patterns/info-unit-groups)

**Describe your issue** 
The current name "info unit group" doesn't help describe the purpose of the component, and may not be meaningful to new users. Consider alternatives. 
 
**Add any additional background info as needed** 
* Note that this would make it more difficult for expert users who have been around a while to find this information.

**Comment by anselmbradford** [comment]
We also have an info-unit-group and info-unit-group2 in cf gov :( 

https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/jinja2/v1/_includes/organisms/info-unit-group.html
https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/jinja2/v1/_includes/organisms/info-unit-group-2.html

**Comment by sonnakim** [comment]
This seems irrelevant as of now — we'd have to update hundreds of files to do this, and there's enough familiarity within the team with this term.
