### ISSUE TITLE
Seal: Needs FEWD to create color swatches

### ISSUE THREAD

**Issue by huetingj** [cfpb/design-system#957]
**Which page is this about?** 
Seal: https://cfpb.github.io/design-system/foundation/seal

**Describe your issue** 
Need FEWD to create beige swatches that can be pulled into/displayed in this table thaannkkk yyooouuu:

![Screen Shot 2020-07-20 at 3 17 11 PM](https://user-images.githubusercontent.com/10562530/87977078-1ab50000-ca9c-11ea-9a1a-b2fa794689c7.png)

Name the swatches:
beige
beige-60
beige-30

**Comment by anselmbradford** [comment]
PR --> https://github.com/cfpb/design-system/pull/1108

**Comment by huetingj** [comment]
YAY!!
