### ISSUE TITLE
Headings: Add missing design specs

### ISSUE THREAD

**Issue by huetingj** [cfpb/design-system#961]
**Which page is this about?** 
Headings: https://cfpb.github.io/design-system/foundation/headings

**Describe your issue** 
Need to list the design specs for the variation headings. 
- Heading with icon
- Eyebrow headings
- Slug heading

**Comment by stephanieosan** [comment]
It looks like the eyebrow headings and slug headings have specs that were added, but the "Heading with icon" variation still needs specs to be written and added.

**Comment by sonnakim** [comment]
For the "Heading with icon" variation, I added some bare-bones text specs and a link to our list of icons - hope that's sufficient!
